<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>第90回五月祭 企画展示経路探索</title>

    <link href="/plugin/css/bootstrap.min.css" rel="stylesheet">
    <link href="/plugin/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/plugin/css/animate.css" rel="stylesheet">
    <link href="/plugin/css/style.css" rel="stylesheet">


    <!-- common_alg -->
    <link href="/css/common_alg.css" rel="stylesheet">

    <!--favicon-->
    <link rel="shortcut icon" href="/img/favicon/favicon.ico" />
</head>

<body>



<div id="wrapper">

    <div id="page-wrapper" class="gray-bg" style="margin-left:0px;">
        <div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox" id="id">

                        <!--ここで高さ変更できる-->
                        <div class="ibox-content">
                            <div class="text-center article-title">
                                <br><br>
                                    <div id="toptitle">
                                        <h1>
                                        <font size="5">このアプリ内で動く<br>
                                        アルゴリズムの紹介</font>
                                        </h1>
                                    </div>
                            </div>


                            <td><div class="section"><h2 class="alg">
                                ざっくりいうと
                            </h2> </div> </td>
                            <br>
                            <p>
                                アルゴリズム班が製作したこのアプリは簡単に言うと、みなさんが訪れたい展示を指定して、それらを最短でまわるような経路を求めるというものです。
                                <br>この最短経路検索には大きく分けて二つのアルゴリズムが使われています。
                            </p>

                            <p>
                                一つ目はすべての二つの展示の組み合わせに対して、最短経路とそのときの所要時間を求めるアルゴリズムです。
                                <br>今回のアプリではグラフ上での二点間を求めるためによく使われるダイクストラ法を使いました。
                                <br>ダイクストラ法によってあらかじめ全展示間の最短での移動時間を計算して保存しておきます。ダイクストラ法については下の方で詳しく書いてあります。
                            </p>
                            <br>
                            <p>
                                二つ目はみなさんが回りたい展示の列と現在地を受け取り、展示を回る順番を全通り列挙して必要な合計時間が一番小さくなるような展示のまわり方を表示するアルゴリズムです。合計時間は一つ目のダイクストラ法で求めておいた二点間の距離を用いて求めます。
                                <br><br>その際、展示時間が固定されているような展示(演劇や演奏など上映時間が決められているもの)がある場合、その展示に間に合うような経路だけ返すようにしてあります。
                                どんなに短い時間でまわれる経路でも現実的に不可能なルートだったら意味がないからですね。
                                <br>
                                <br>
                                まとめると次のようになります。
                                <br>
                            </p>
                                <td><div class="rule_outside">
                                    <div class="rule"><strong>~このアプリの仕組み~
                                        <br>
                                        <br>
                                        1. 二つの展示の間の最短移動時間をすべての組み合わせに対してあらかじめ計算しておいて、
                                        <br>
                                        <br>
                                        2.みなさんが行きたい展示を並べ替えて求めておいた時間を合計して一番最短で回ることのできる経路を表示する！</strong>
                                    </div>
                                    </div> </td>
                                    <br>
                            <td><div class="section"><h2 class="alg">
                                最短路を求める
                            </h2> </div> </td>
                            <br>
                            <p>
                                すべての点の間の最短経路とその所要時間を求めておくのが一つ目のやるべきことでした。
                                この問題を私たちは「ダイクストラ法」というアルゴリズムを用いて解決しました。
                                <br>
                                以下、ダイクストラ法の説明をしていきたいと思いますが、その前にグラフについて簡単に説明しておきます。
                                <br>
                                <br>
                            グラフと聞いて多くの人が最初に思い浮かべるのは棒グラフや折れ線グラフ、中高生であれば関数のグラフなどではないでしょうか。
                            今回のアルゴリズムでいうグラフとはこれらとは異なるもので、大まかに言うと頂点が辺で繋がれているような地図のようなものです。
                            <br>
                            <br>
                            単純なグラフには各辺には数字が振られていないのですが、以下のように辺に数字が割り当てられているグラフもあり、これを重み付きグラフといいます。
                            今回のアルゴリズムではこの重み付きグラフを使います。ちなみに重み付きグラフはネットワークといい、割り当てられた数字を重みと言います。
                            今回のアプリケーションでは本郷キャンパスの各展示や交差点を頂点に、道を辺として重み付きグラフを作成しました。
                            重み付きグラフなので先ほども述べた通り各辺には数字が割り当てられますが、ここではその道を移動するのにかかる時間を割り当てました。
                            </p>
                            <br>
                            <p>
                                ここまできたらやるべきことがなんとなくわかってきたと思います。
                                二つの頂点をつなぐ道の中で辺に振られている重みの合計が最小になるような道順を見つければいいということですね。
                                <br>では試しに下のグラフについて、頂点1から頂点5までの最短経路を探してみましょう。
                            </p>
                            <br>
                            <div align="center">
                                <img src="/img/graph.png" class="alg_img">
                            </div>

                            <p>
                                <br>
                                見つけられたでしょうか？最短経路は頂点1,2,3,5の順にたどっていくというものですが、大事なのは答えではなくその求め方にあります。
                                おそらく多くの方はしらみつぶしに片っ端から1から5に行ける道を辿って行って最短経路を求めたと思います。
                                <br><br>
                                このグラフでは規模が小さいので全部しらみつぶしに探して行ってもそこまで負担ではないのですが、想像してみてください。本郷キャンパスにはもっとたくさんの展示と道があります。そのグラフ上で先ほどと同じことをあなたはしたいでしょうか？また人間がやらないとしても、一つ一つ試していくのはコンピュータでも結構な時間がかかってしまいます。
                            </p>

                            <p>
                                というように、グラフが大きくなってしまう今回のアプリでは残念ながら最短経路を一つ一つ試していって求めるという方法は使うことができません。ここで、ようやくダイクストラ法の出番です。
                            </p>
                            <br>

                            <td><div class="section"><h2 class="alg">
                                具体的な手順
                            </h2> </div> </td>
                            <br>
                            <p>
                                ダイクストラ法では、以下の二つのグループを用意します。
                                「最短経路が決まってないグループ」と「最短経路が決まったグループ」です。
                                この二つのグループに各頂点を出したり入れたりして最短経路を確定させていく、というのがダイクストラ法の大まかな流れとなっています。
                                <br>
                                それでは具体的な手順を見ていきましょう。
                            <p>
                                ダイクストラ法を行うにあたって、まず最初にやるべきことは、始点 (スタート地点)と終点 (ゴール地点)を決めておくことです。
                                今回のアプリではすべての点の間の最短経路とその移動時間を求める必要があるので、この始点と終点を入れ替えて実行、入れ替えて実行...を繰り返すことで
                                すべてのパターンに対して計算を行っておくという仕組みです。このように始点と終点が与えられて、いよいよダイクストラ法が動き始めます。
                                <br><br>
                                最初、すべての頂点を「最短経路が決まってないグループ」に入れておきます。
                                各頂点の始点からの暫定での最短所要時間をすべて無限大に大きくしておき、始点の始点からの到達所要時間は0としておきます。
                                それから以下のルールに従って点をグループからグループへ移動させていきます。
                            </p>
                            <br>
                            <td><div class="rule_outside">
                                <div class="rule" ><strong>~ルール~
                                    <br>
                                    <br>
                                    1. 最短経路が決まっていないグループのうち最短経路の所要時間が一番短いものを「最短経路が決まったグループ」に入れる。
                                    <br><br>
                                    2.  移した点と繋がっている点に対して、その点の暫定の最短所要時間よりも移した点を経由して行った場合の所要時間のほうが短かったら暫定の最短所要時間を更新します。
                                    <br><br>
                                    3.  終点が「最短経路が決まったグループ」に移動したら終了。まだ「最短経路が決まっていないグループ」にある場合は1に戻る。
                                    </strong>
                                </div>
                                </div> </td>
                            <p>
                                <br>
                                とはいえ文章だけでは分かりづらいので、実際に先ほど考えたグラフについてダイクストラ法を適用してみてグループ間の移動ルールを理解してみましょう。頂点はさきほどと同じく1から5の最短経路を求めるという設定でやってみます。

                            </p>
                            <br>
                            <td><div class="section"><h2 class="alg">
                                やってみよう！
                            </h2> </div> </td>
                            <br>
                            <p>まず暫定の最短の所要時間は頂点1だけ0で、それ以外は無限大なので一番所要時間の小さい頂点1が「最短経路が決まったグループ」に移されます。
                            </p>

                            <p>次に1から移動できる点2と3について、現在の暫定での最短所要時間（どちらも無限大）よりも頂点1から2や3に行った方が所要時間は小さくなるので暫定の最短所要時間を更新します。頂点2は頂点1からいくと50分、頂点3は頂点1からいくと80分であり、頂点1までの所要時間は0なので頂点2,3の暫定の最短所要時間はそれぞれ50分,80分になります。（これで１ステップ終了）

                            </p>
                            <p>
                                同様に「最短経路が決まっていないグループ」（頂点は2,3,4,5が残ってる）のうち一番暫定最短距離が短いもの（すなわち頂点2）を「最短経路が決まったグループ」に移します。
                                頂点2からいける点（頂点3,頂点4）に対して同様に最短での所要時間を更新します。
                                頂点4については無限なので更新するのは当たり前ですが（更新すると50+15で65分になる）、3は1からもいけているのでそれよりも短い時間でいけるかを考えなければいけません。今回1から3に直接行くのにかかる80分（暫定での最短）よりも1から2に行って3に行くルート（2への最短所要時間である50分と、そこからかかる20分を足して70分）を比べて70分の方が短いので3の暫定の最短所要時間を80分から70分に更新することになります。（2ステップ終了）
                            </p>
                            <p>
                                同様に「最短経路が決まっていないグループ」（頂点は3,4,5が残ってる）のうち一番暫定最短距離が短いもの（すなわち頂点4）を最短距離が決まったグループに移します。
                                また4からいける点に対して最短所要時間を更新して.......と続けていき、5が「最短経路決定済みグループ」に移動したら終了です。
                                各ステップにつき一つずつ頂点の最短経路が決定していくイメージです。
                            </p>
                            <br>
                            <td><div class="section"><h2 class="alg">
                                計算時間の話
                            </h2> </div> </td>
                            <br>
                            <p>この方法で最短経路を求めると、最短経路が決まっているかどうかをで分割するグループの実装の仕方にもよりますが、辺の数の二乗ぐらいの計算時間がかかります。
                                <br><br>言い換えると、辺の数を10倍にすると計算時間は100倍に、100倍すると10000倍になるということです。
                                <br><br>詳しくは計算時間のオーダーという問題に関わってくるのでここでは詳しくは説明できませんが、最初にみなさんがやろうとした(であろう)、経路の候補を一つ一つすべて試していく愚直な方法では辺の数の階乗ぐらいの計算時間がかかります。
                                <br><br>少し試してみるとわかるように階乗の方が圧倒的に早く大きくなっていくことがわかります。下に二つの方法の枝の数に対する計算時間の増え方をまとめました。
                            </p>
                            <br>
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>アルゴリズム \ 辺の数</th>
                                        <th>
                                            1本
                                        </th>
                                        <th>
                                            2本
                                        </th>
                                        <th>
                                            3本
                                        </th>
                                        <th>
                                            5本
                                        </th>
                                        <th>
                                            7本
                                        </th>
                                        <th>
                                            10本
                                        </th>
                                        <th>
                                            15本
                                        </th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <th>ダイクストラ法</th>
                                        <td>1 × 1 = 1</td>
                                        <td>2 × 2 = 4</td>
                                        <td>3 × 3 = 9</td>
                                        <td>5 × 5 = 25</td>
                                        <td>7 x 7 = 49</td>
                                        <td>10 × 10 = 100</td>
                                        <td>15 × 15 = 225</td>
                                    </tr>
                                    <tr>
                                        <th>一つずつ試す方法</th>
                                        <td>1 ! = 1</td>
                                        <td>2 ! = 2</td>
                                        <td>3 ! = 6</td>
                                        <td>5 ! = 120</td>
                                        <td>7 ! = 5040</td>
                                        <td>10 ! = 3628800</td>
                                        <td>15 ! = 1307674368000</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>

                            <p>
                                <br>
                            <p>
                                このように、枝の数が大きくなればなるほどダイクストラ法の方が早く計算が終わることがわかります。
                                今回のように辺の数が大きい場合にはダイクストラ法が有効、ということですね。
                                <br>
                                <br>
                                一見とっつきにくそうな印象を持たれがちなアルゴリズムですが、このような応用例を通して少しでも身近に感じていただけたら嬉しいです。
                            </p>

                            <hr>


                        </div>
                    </div>
                </div>

            </div>
        </div>
            <!--<div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>-->
            <div class="footer">
                <div class="pull-right">
                    東京大学工学部応用物理系（物理工学科・計数工学科）
                </div>
                <div class="pull-left">
                    <strong>Applied Physics, University of Tokyo</strong> for May Festival 2017
                </div>
            </div>



    </div>
</div>


<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<!-- Mainly scripts -->
<script src="/plugin/js/jquery-3.1.1.min.js"></script>
<script src="/plugin/js/bootstrap.min.js"></script>
<script src="/plugin/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="/plugin/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="/assets-admin/js/inspinia.js"></script>
<script src="/plugin/js/plugins/pace/pace.min.js"></script>

<!-- Steps -->
<script src="/plugin/js/plugins/steps/jquery.steps.min.js"></script>

<!-- Jquery Validate -->
<script src="/plugin/js/plugins/validate/jquery.validate.min.js"></script>

<!-- iCheck -->
<script src="/plugin/js/plugins/iCheck/icheck.min.js"></script>

<!-- Clock picker -->
<script src="/plugin/js/plugins/clockpicker/clockpicker.js"></script>

<!-- Select2 -->
<script src="/plugin/js/plugins/select2/select2.full.min.js"></script>

<!-- Chosen -->
<script src="/plugin/js/plugins/chosen/chosen.jquery.js"></script>

<!-- Sweet alert -->
<script src="/plugin/js/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    $('.chosen-select').chosen({width: "15%"});

    $(document).ready(function(){
        $("#wizard").steps();
        $("#form").steps({
            bodyTag: "fieldset",
            onStepChanging: function (event, currentIndex, newIndex)
            {
                // Always allow going backward even if the current step contains invalid fields!
                if (currentIndex > newIndex)
                {
                    return true;
                }

                // Forbid suppressing "Warning" step if the user is to young
                /*
                 if (newIndex === 3 && Number($("#age").val()) < 18)
                 {
                 return false;
                 }
                 */
                var form = $(this);

                // Clean up if user went backward before
                if (currentIndex < newIndex)
                {
                    // To remove error styles
                    $(".body:eq(" + newIndex + ") label.error", form).remove();
                    $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                }

                // Disable validation on fields that are disabled or hidden.
                form.validate().settings.ignore = ":disabled,:hidden";

                // Start validation; Prevent going forward if false
                return form.valid();
            },
            onStepChanged: function (event, currentIndex, priorIndex)
            {
                // Suppress (skip) "Warning" step if the user is old enough.
                if (currentIndex === 2 && Number($("#age").val()) >= 18)
                {
                    $(this).steps("next");
                }

                /*
                 // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                 if (currentIndex === 2 && priorIndex === 3)
                 {
                 $(this).steps("previous");
                 }
                 */
            },
            onFinishing: function (event, currentIndex)
            {
                var form = $(this);

                var j = 0;

                for(i=1;i<10;i++) {
                    name = "input" + i;
                    hidden = $('[name=' + name + ']').val();
                    if (hidden) {
                        j = 1;
                        break;
                    }
                    console.log(name);
                    console.log(hidden);
                }

                // Disable validation on fields that are disabled.
                // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                form.validate().settings.ignore = ":disabled";

                // Start validation; Prevent form submission if false

                if (j == 1) {
                    return form.valid();
                } else {
                    swal({
                        title: "企画が選択されてません",
                        text: "検索するには、企画を１つ以上選択してください",
                        type: "warning",
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "OK",
                        closeOnConfirm: false
                    });

                }
            },
            onFinished: function (event, currentIndex)
            {
                var form = $(this);

                // Submit form input
                form.submit();
            }
        }).validate({
            errorPlacement: function (error, element)
            {
                element.before(error);
            },
            rules: {
                confirm: {
                    equalTo: "#password"
                }
            }
        });

        //iCheck
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
        $('input').on('ifChecked', function(event){
            $("#jQuery1").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQuery2").toggle();
        });

        //clockpicker
        var input = $('#clock1').clockpicker({
            placement: 'bottom',
            align: 'left',
            //autoclose: true,
            'default': 'now'
        });
        $('#clock2').clockpicker({
            placement: 'bottom',
            align: 'left',
            //autoclose: true,
        });

        $('#input-clock1').change(function() {
            if ($('#input-clock1').val)
                $("#clockText1").text($('#input-clock1').val());
        });
        $('#input-clock2').change(function() {
            $("#clockText2").text($('#input-clock2').val());
        });

        //select2
        $(".select2_demo_1").select2();
        $(".select2_demo_2").select2();
        $(".select2_demo_3").select2({
            placeholder: "Select a state",
            allowClear: true
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox1").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush1").click(function(){
            $("#jQueryPush1").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox1").toggle();
        });

        $("#jQueryBox1").click(function(){
            $("#jQueryPush1").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox1").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox2").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush2").click(function(){
            $("#jQueryPush2").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox2").toggle();
        });

        $("#jQueryBox2").click(function(){
            $("#jQueryPush2").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox2").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox3").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush3").click(function(){
            $("#jQueryPush3").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox3").toggle();
        });

        $("#jQueryBox3").click(function(){
            $("#jQueryPush3").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox3").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox4").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush4").click(function(){
            $("#jQueryPush4").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox4").toggle();
        });

        $("#jQueryBox4").click(function(){
            $("#jQueryPush4").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox4").toggle();
        });
    });

    //企画の項目を選んで表示
    $(function() {


        //キーワード検索
        $("#search_pid").on("select2:select", function () {
            pid = $(this).val();

            $.each(pid,
                function(index, elem) {
                    console.log(elem);

                    val = "#form_pid" + elem;

                    console.log(val);
                    $(val).show();

                    val1 = "input" + elem;
                    a = $('[name=' + val1 + ']').val(elem);
                    console.log(a);
                }
            );
        });

        //キーワード検索　消す
        $("#search_pid").on("select2:unselect", function (e) {
            val = "#form_pid" + e.params.data.id;
            //console.log(val);
            console.log(val);
            //console.log(e);


            $(val).hide();
            $('[name=val]').val();


        });



        $("#dropmenu").click(function (e) {
            e.stopPropagation(); // 追加
        });
        $("#dropmenu li").click(function (e) {
            e.stopPropagation(); // 追加
        });


    });

    $(function() {
        $("#pid1 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid1").toggle();
            $("#pid1 a").toggleClass("highlight");
            $("[name=input1]").val("1");
        });
        $("#pid2 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid2").toggle();
            $("#pid2 a").toggleClass("highlight");
            $("[name=input2]").val(2);
        });
        $("#pid3 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid3").toggle();
            $("#pid3 a").toggleClass("highlight");
            $("[name=input3]").val(3);
        });
        $("#pid4 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid4").toggle();
            $("#pid4 a").toggleClass("highlight");
            $("[name=input4]").val(4);
        });
        $("#pid5 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid5").toggle();
            $("#pid5 a").toggleClass("highlight");
            $("[name=input5]").val(5);
        });
        $("#pid6 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid6").toggle();
            $("#pid6 a").toggleClass("highlight");
            $("n[ame=input6]").val(6);
        });
        $("#pid7 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid7").toggle();
            $("#pid7 a").toggleClass("highlight");
            $("[name=input7]").val(7);
        });
        $("#pid8 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid8").toggle();
            $("#pid8 a").toggleClass("highlight");
            $("[name=input8]").val(8);
        });
        $("#pid9 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid9").toggle();
            $("#pid9 a").toggleClass("highlight");
            $("[name=input9]").val(9);
        });
        $("#pid10 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid10").toggle();
            $("#pid10 a").toggleClass("highlight");
            $("[name=input10]").val(10);
        });
        $("#pid11 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid11").toggle();
            $("#pid11 a").toggleClass("highlight");
            $("[name=input11]").val(11);
        });
        $("#pid12 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid12").toggle();
            $("#pid12 a").toggleClass("highlight");
            $("[name=input12]").val(12);
        });
        $("#pid13 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid13").toggle();
            $("#pid13 a").toggleClass("highlight");
            $("[name=input13]").val(13);
        });
        $("#pid14 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid14").toggle();
            $("#pid14 a").toggleClass("highlight");
            $("[name=input14]").val(14);
        });
        $("#pid15 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid15").toggle();
            $("#pid15 a").toggleClass("highlight");
            $("[name=input15]").val(15);
        });
        $("#pid16 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid16").toggle();
            $("#pid16 a").toggleClass("highlight");
            $("[name=input16]").val(16);
        });
        $("#pid1 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid17").toggle();
            $("#pid17 a").toggleClass("highlight");
            $("[name=input17]").val(17);
        });
        $("#pid18 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid18").toggle();
            $("#pid18 a").toggleClass("highlight");
            $("[name=input18]").val(18);
        });
        $("#pid19 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid19").toggle();
            $("#pid19 a").toggleClass("highlight");
            $("[name=input19]").val(19);
        });
        $("#pid20 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid20").toggle();
            $("#pid20 a").toggleClass("highlight");
            $("[name=input20]").val(20);
        });
        $("#pid21 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid21").toggle();
            $("#pid21 a").toggleClass("highlight");
            $("[name=input21]").val(21);
        });
        $("#pid22 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid22").toggle();
            $("#pid22 a").toggleClass("highlight");
            $("[name=input22]").val(22);
        });
        $("#pid23 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid23").toggle();
            $("#pid23 a").toggleClass("highlight");
            $("[name=input23]").val(23);
        });
        $("#pid24 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid24").toggle();
            $("#pid24 a").toggleClass("highlight");
            $("[name=input24]").val(24);
        });
    });

    $(document).ready(function () {

        $('#ap').click(function (e) {
            e.stopPropagation();
            swal({
                title: "工学部応用物理系ってなあに？",
                text: "You will not be able to recover this imaginary file!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "詳細が知りたい！",
                closeOnConfirm: false,
                allowOutsideClick: true,
            }, function () {
                window.location.href = "";
            });
        });
    });

    //ページ内ゆっくり遷移

    $(function(){
        $('a[href="#id"]').click(function(){
            var speed = 500;
            var href= $(this).attr("href");
            var target = $('#id');
            var position = target.offset().top;
            $("html, body").animate({scrollTop:position}, speed, "swing");
            return false;
        });
    });




    /*
     $("#pid<?php echo $i; ?> a").click(function () {
     $("#form_pid<?php echo $i; ?>").toggle(
     function () {
     $("#pid<?php echo $i; ?> a").css("background-color", "#ff1111");
     },
     function () {
     $("#pid<?php echo $i; ?> a").css("background-color","#ffe222");
     }
     );
     });
     */

    //var $eventSelect = $("#search_pid");

    //$eventSelect.on("change", function (e) { log("change"); });

    //キーワード検索用

    /*
     $('#search_pid').on('select2:select',function(e){
     val = ($(this).val());
     console.log(val);
     });
     */




    /*$("#form_pid".val).toggle();
     e.stopPropagation(); // 追加
     */
    //$("#pid".val." a").toggleClass("highlight");
    //$('[name="input".val]').val(<?php echo $i; ?>);



</script>

</body>

</html>
