<li class="list-group-item last-conf" id="<?php echo $this->data['pt_pid']; ?>">
    <span class="pull-right pe-7s-close delete-btn" onclick="$('input[value=' + $(this).parent().prop('id') + ']').prop('checked', false); $(this).parent().remove();"></span>
    <span class="pull-right body-text no-margins" style="width: 30%;">
        <?php echo $this->data['pd_body']; ?>
    </span>
    <span class="pull-right m-r-lg place-text">
        <?php echo $this->data['pp_place']; ?>
    </span>
    <span class="pull-right stay-text">
        <select name="time<?php echo $this->data['pt_pid']; ?>">
            <option value="5" <?php echo ($this->data['pt_time'] == 5) ? 'selected=""' : ''; ?>>5</option>
            <option value="10" <?php echo ($this->data['pt_time'] == 10) ? 'selected=""' : ''; ?>>10</option>
            <option value="15" <?php echo ($this->data['pt_time'] == 15) ? 'selected=""' : ''; ?>>15</option>
            <option value="20" <?php echo ($this->data['pt_time'] == 20) ? 'selected=""' : ''; ?>>20</option>
            <option value="25" <?php echo ($this->data['pt_time'] == 25) ? 'selected=""' : ''; ?>>25</option>
            <option value="30" <?php echo ($this->data['pt_time'] == 30) ? 'selected=""' : ''; ?>>30</option>
            <option value="35" <?php echo ($this->data['pt_time'] == 35) ? 'selected=""' : ''; ?>>35</option>
            <option value="40" <?php echo ($this->data['pt_time'] == 40) ? 'selected=""' : ''; ?>>40</option>
            <option value="45" <?php echo ($this->data['pt_time'] == 45) ? 'selected=""' : ''; ?>>45</option>
            <option value="50" <?php echo ($this->data['pt_time'] == 50) ? 'selected=""' : ''; ?>>50</option>
            <option value="55" <?php echo ($this->data['pt_time'] == 55) ? 'selected=""' : ''; ?>>55</option>
            <option value="60" <?php echo ($this->data['pt_time'] == 60) ? 'selected=""' : ''; ?>>60</option>
            <option value="65" <?php echo ($this->data['pt_time'] == 65) ? 'selected=""' : ''; ?>>65</option>
            <option value="70" <?php echo ($this->data['pt_time'] == 70) ? 'selected=""' : ''; ?>>70</option>
            <option value="75" <?php echo ($this->data['pt_time'] == 75) ? 'selected=""' : ''; ?>>75</option>
            <option value="80" <?php echo ($this->data['pt_time'] == 80) ? 'selected=""' : ''; ?>>80</option>
            <option value="85" <?php echo ($this->data['pt_time'] == 85) ? 'selected=""' : ''; ?>>85</option>
            <option value="90" <?php echo ($this->data['pt_time'] == 90) ? 'selected=""' : ''; ?>>90</option>
            <option value="95" <?php echo ($this->data['pt_time'] == 95) ? 'selected=""' : ''; ?>>95</option>
            <option value="100" <?php echo ($this->data['pt_time'] == 100) ? 'selected=""' : ''; ?>>100</option>
            <option value="105" <?php echo ($this->data['pt_time'] == 105) ? 'selected=""' : ''; ?>>105</option>
            <option value="110" <?php echo ($this->data['pt_time'] == 110) ? 'selected=""' : ''; ?>>110</option>
            <option value="115" <?php echo ($this->data['pt_time'] == 115) ? 'selected=""' : ''; ?>>115</option>
            <option value="120" <?php echo ($this->data['pt_time'] == 120) ? 'selected=""' : ''; ?>>120</option>

        </select>
        分
    </span>
    <span class="pull-right m-r-lg time-text" style="width:40px;">
        <?php echo ($this->data['pt_start']) ? $this->data['pt_start'] : '終日'; ?>
    </span>
    <label> <?php echo $this->data['pd_label']; ?> </label>
</li>
