<div id="tab-1" class="tab-pane active">
    <div class="panel-body">
        <div class="full-height-scroll">
            <h3 class="phone-display p-sm b-r-md bg-muted text-center">
                キーワード検索
            </h3>
            <input id="search1" type="text" class="form-control" value="" placeholder="企画名・建物名・団体名で検索できます。"/>
            <div class="m-t-sm search-in">
                <ul id="search-all" class="list-group clear-list m-t">
                    <?php foreach ($this->data['data'] as $key => $item) : ?>
                        <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                            <span class="exp-text">
                                <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_ps_pid<?php echo $item['ps_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                            </span>
                            <span class="body-text">
                                <?php echo $item['pd_body']; ?>
                            </span>
                            <span class="place-text">
                                <?php echo $item['pp_place']; ?>
                            </span>
                            <span class="time-text">
                                <?php echo ($item['pt_start']) ? $item['pt_start'] : '終日'; ?>
                            </span>
                            <span style="display: none;">
                                <?php echo $item['pp_place']," ",$item['pd_label_kana']," ",$item['pd_place_kana']," ",$item['pd_body_kana']; ?>
                            </span>
                            <div class="check-text i-checks">
                                <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p" name="select-p"> <?php echo $item['pd_label']; ?> </label>
                            </div>
                        </li>
                    <?php endforeach; ?>

                </ul>
            </div>
        </div>
    </div>
</div>
<div id="tab-2" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            ジャンル検索
        </h3>
        <div class="full-height-scroll">
            <div class="table-responsive">

                <div class="row">
                    <?php foreach ($this->data['genre'] as $key => $val) : ?>
                        <div class="col-sm-6 col-md-4">
                            <div id="PushGenre<?php echo $val['name']; ?>" class="genre-push contact-box m-b-sm b-r-md" style="background-image: url(/img/logo/logo_<?php echo $val['name']; ?>.png);background-size: cover; cursor: pointer; position: relative;">
                                <input type="hidden" name="name" value="<?php echo $val['name']; ?>">
                                <h3><strong><?php echo $val['label']; ?></strong></h3>
                                <i class="fa fa-5x fa-<?php echo $this->icon[$val['name']]; ?> m-md" style="color: rgba(255,255,255,0.5); position: absolute; top: 0; right: 0;"></i>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

                <?php foreach ($this->data['genre'] as $key => $val) : ?>
                    <div id="BoxGenre<?php echo $val['name']; ?>" class="genre-box contact-box" style="background-image: url(/img/logo/logo_<?php echo $val['name']; ?>.png); background-size: cover;">
                        <div class="transparent">
                            <?php foreach ($val['info'] as $key2 => $val2) : ?> <!--$key2は数値-->
                                <?php echo ($key2%3 == 0) ? '<div class="row">' : ''; ?>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <button type="button" class="btn btn-open btn-<?php echo $this->color[$key2%5]; ?> btn-lg btn-outline m-b-md btn-block">
                                        <?php echo $val2['gd_detail_label']; ?>
                                        <input type="hidden" name="btn-val" value="genre<?php echo $val2['gd_pid']; ?>">
                                    </button>
                                    <div class="select-box m-b-md" id="genre<?php echo $val2['gd_pid']; ?>">
                                        <ul class="list-group clear-list m-t">
                                        <?php $i = 0; foreach ($this->data['data'] as $name => $item) : ?>
                                            <?php if ($item['pd_genre1'] == $val['name'] && $item['pd_genre2'] == $val2['gd_detail']) : ?>
                                                <li class="list-group-item <?php echo ($i == 0) ? 'fist-item' : ''; ?>">
                                                            <span class="pull-right" style="text-align: right;">
                                                                <button type="button" class="btn btn-info btn-xs btn-modal" data-toggle="modal" data-target="#Modal_ps_pid<?php echo $item['ps_pid']; ?>" value="<?php echo $item['ps_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                                            </span>
                                                    <span class="pull-right m-r-xs">
                                                                <?php echo $item['pt_start']; ?>
                                                            </span>
                                                    <div class="i-checks">
                                                        <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p"> <i></i> <?php echo $item['pd_label']; ?> </label>
                                                    </div>
                                                </li>
                                            <?php ++$i; endif; ?>
                                        <?php endforeach; ?>
                                        </ul>
                                        <?php echo ($i == 0) ? '企画はありません。' : ''; ?>
                                    </div>
                                </div>
                                <?php echo ($key2%3 == 2 || !$val['info'][$key2+1]) ? '</div>' : ''; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


<div id="tab-3" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            エリア検索
        </h3>
        <div class="row push-outside">
            <?php foreach ($this->data['area'] as $key => $val) : ?>
                <div class="col-xs-12 col-sm-6">
                    <div id="PushArea<?php echo $val['name']; ?>" class="area-push contact-box m-b-sm b-r-md" style="background-image: url(/img/logo/<?php echo $val['name']; ?>.png);background-size: cover; cursor: pointer; position: relative;">
                        <input type="hidden" name="name" value="<?php echo $val['name']; ?>">
                        <h3><strong><?php echo $val['label']; ?></strong></h3>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <?php foreach ($this->data['area'] as $key => $val) : ?>
            <div id="BoxArea<?php echo $val['name']; ?>" class="area-box contact-box" style="background-image: url(/img/logo/<?php echo $val['name']; ?>.png); background-size: cover;">
                <div class="transparent">
                    <?php foreach ($val['info'] as $key2 => $val2) : ?> <!--$key2は数値-->
                        <?php echo ($key2%3 == 0) ? '<div class="row">' : ''; ?>
                        <div class="col-xs-12 col-sm-6 col-md-4">
                            <button type="button" class="btn btn-open btn-<?php echo $this->color[$key2%5]; ?> btn-lg btn-outline m-b-md btn-block">
                                <?php echo $val2['bd_p_label2']; ?>
                                <input type="hidden" name="btn-val" value="area<?php echo $val2['bd_pid']; ?>">
                            </button>
                            <div class="select-box m-b-md" id="area<?php echo $val2['bd_pid']; ?>">
                                <ul class="list-group clear-list m-t">
                                    <?php $i = 0; foreach ($this->data['data'] as $name => $item) : ?>
                                        <?php if ($item['pp_name1'] == $val['name'] && $item['pp_name2'] == $val2['bd_p_name2']) : ?>
                                            <li class="list-group-item <?php echo ($i == 0) ? 'fist-item' : ''; ?>">
                                                <span class="pull-right" style="text-align: right;">
                                                    <button type="button" class="btn btn-info btn-xs btn-modal" data-toggle="modal" data-target="#Modal_ps_pid<?php echo $item['ps_pid']; ?>" value="<?php echo $item['ps_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                                </span>
                                                <span class="pull-right m-r-xs">
                                                    <?php echo $item['pt_start']; ?>
                                                </span>
                                                <div class="i-checks">
                                                    <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p"> <?php echo $item['pd_label']; ?> </label>
                                                </div>
                                            </li>
                                            <?php ++$i; endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                                <?php echo ($i == 0) ? '企画はありません。' : ''; ?>
                            </div>
                        </div>
                        <?php echo ($key2%3 == 2 || !$val['info'][$key2+1]) ? '</div>' : ''; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; unset($this->info) ?>


</div>
</div>
<div id="tab-4" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            おすすめ企画
        </h3>
        <div class="full-height-scroll">
            <div class="search-in2">
                <ul class="list-group clear-list m-t">

                <?php $i = 0; foreach ($this->data['data'] as $key => $item) : ?>
                    <?php if ($item['pd_rec_flg']) : ?>
                    <li class="list-group-item <?php echo ($i == 0) ? 'fist-item' : ''; ?>">
                        <span class="exp-text">
                            <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_ps_pid<?php echo $item['ps_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                </span>
                        <span class="body-text">
                                    <?php echo $item['pd_body']; ?>
                                </span>
                        <span class="place-text">
                                    <?php echo $item['pp_place']; ?>
                                </span>
                        <span class="time-text">
                                    <?php echo ($item['pt_start']) ? $item['pt_start'] : '終日'; ?>
                                </span>
                        <div class="check-text i-checks">
                            <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p"> <?php echo $item['pd_label']; ?> </label>
                        </div>
                    </li>
                    <?php $i++; endif; ?>
                <?php endforeach; ?>
                    <?php if ($i==0) : ?>指定した時刻に開催されるおすすめ企画はありません。<?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="tab-5" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            ピックアップ企画
        </h3>
        <div class="full-height-scroll">
            <div class="search-in2">
                <ul class="list-group clear-list m-t">
                    <?php $i=0; foreach ($this->data['data'] as $key => $item) : ?>
                        <?php if ($item['pd_pickup_flg']) : ?>
                            <li class="list-group-item <?php echo ($i == 0) ? 'fist-item' : ''; ?>">
                        <span class="exp-text">
                            <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_ps_pid<?php echo $item['ps_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                </span>
                                <span class="body-text">
                                    <?php echo $item['pd_body']; ?>
                                </span>
                                <span class="place-text">
                                    <?php echo $item['pp_place']; ?>
                                </span>
                                <span class="time-text">
                                    <?php echo ($item['pt_start']) ? $item['pt_start'] : '終日'; ?>
                                </span>
                                <div class="check-text i-checks">
                                    <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p"> <?php echo $item['pd_label']; ?> </label>
                                </div>
                            </li>
                        <?php $i++; endif; ?>
                    <?php endforeach; ?>
                    <?php if ($i==0) : ?>指定した時刻に開催されるピックアップ企画はありません。<?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="tab-6" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            学術企画
        </h3>
        <div class="full-height-scroll">
            <div class="search-in2">
                <ul class="list-group clear-list m-t">
                    <?php $i = 0; foreach ($this->data['data'] as $key => $item) : ?>
                        <?php if ($item['pd_academic_flg']) : ?>
                            <li class="list-group-item <?php echo ($i == 0) ? 'fist-item' : ''; ?>">
                        <span class="exp-text">
                            <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_ps_pid<?php echo $item['ps_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                </span>
                                <span class="body-text">
                                    <?php echo $item['pd_body']; ?>
                                </span>
                                <span class="place-text">
                                    <?php echo $item['pp_place']; ?>
                                </span>
                                <span class="time-text">
                                    <?php echo ($item['pt_start']) ? $item['pt_start'] : '終日'; ?>
                                </span>
                                <div class="check-text i-checks">
                                    <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p"> <?php echo $item['pd_label']; ?> </label>
                                </div>
                            </li>
                        <?php $i++; endif; ?>
                    <?php endforeach; unset($this->data); ?>
                    <?php if ($i==0) : ?>指定した時刻に開催される学術企画はありません。<?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){

        $('input#search1').on('keyup', function(){
            console.log($(this).val());
            Search($(this).val());
        });

    });

    function Search(keyword) {

        var regExp = new RegExp(keyword);

        $('#search-all').find('li').hide().each(function(){
            var li = $(this);
            $(this).find('label').each(function(){
                if ($(this).text().match(regExp)) {
                    li.show();
                }
            });
            $(this).find('span').each(function(){
                if ($(this).text().match(regExp)) {
                    li.show();
                }
            });
        });
    }

    $(function(){
    //iCheck
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });

    //genre
    $(function(){
        // 「id="jQueryBox"」を非表示
        $(".genre-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".genre-push").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $(".genre-push").hide();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#BoxGenre" + key).show();
        });
        $(".genre-box").click(function(e){
            e.stopPropagation();
            $(".genre-push").show();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $(".genre-box").hide();
        });
    });

    //area
    $(function(){
    // 「id="jQueryBox"」を非表示
        $(".area-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".area-push").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $(".area-push").hide();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#BoxArea" + key).show();
        });

        $(".area-box").click(function(e){
            e.stopPropagation();
            $(".area-push").show();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $(".area-box").hide();
        });
    });

    $(function(){
    // 「id="jQueryBox"」を非表示
        $(".select-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".btn-open").click(function(e){
            e.stopPropagation();
            var key = $(this).find('input[name="btn-val"]').val();
            //$('.select-box').hide();
            $("div#" + key).slideToggle('fast');
        });
        $(".btn-modal").click(function(event) {
            event.stopPropagation();
            $("#Modal_ps_pid" + $(this).val()).modal('show');
        });
    });

    $(function() {
        $('.last-conf').hide();

        $('input.select-p').on('ifChecked', function(event) {
            var val = $(this).val();
            console.log(val);
            $('input[value="' + val + '"]').iCheck('check');
            $('li#' + val).show();
        });

        $('input.select-p').on('ifUnchecked', function(event) {
            var val = $(this).val();
            console.log(val);
            $('input[value="' + val + '"]').iCheck('uncheck');
            $('li#' + val).hide();
        });
    });
</script>