<style>

    .genre-push,
    .area-push {
        height: 200px;
        /*color: #ffffe0;*/
        font-weight: normal;
        transition: .2s;
        cursor: pointer;
        position: relative;
    }
    #BoxGenreexhibition {
        background-color: rgba(112, 194, 163, 0.25);
    }
    #PushGenreexhibition {
        background-color: #70c2a3;
    }
    #BoxGenremusic {
        background-color: rgba(234, 209, 82, 0.25);
    }
    #PushGenremusic {
        background-color: #ead152;
    }
    #BoxGenreshop {
        background-color: rgba(161, 203, 237, 0.25);
    }
    #PushGenreshop {
        background-color: #a1cbed;
    }
    #BoxGenreperformance {
        background-color: rgba(243, 162, 159, 0.25);
    }
    #PushGenreperformance {
        background-color: #f3a29f;
    }
    #BoxGenrejoin {
        background-color: rgba(191, 154, 198, 0.25);
    }
    #PushGenrejoin {
        background-color: #bf9ac6;
    }
    #BoxGenrelecture {
        background-color: rgba(238, 189, 128, 0.25);
    }
    #PushGenrelecture {
        background-color: #eebd80;
    }
    .genre-push:hover,
    .area-push:hover {
        filter:brightness(1.1);
    }
    .genre-push img {
        height: 100%;
        position: absolute;
        right: 0;
        left: 0;
        top: 10px;
        bottom: 10px;
        margin: auto;
        opacity: 0.9;
    }
    #jQueryPush2 {
        z-index:3;
    }
    #jQueryBox2 {
        z-index:1;
    }
    .area-box.contact-box,
    .genre-box.contact-box {
        height:458px;
        margin: 0;
        padding: 0;
        border-radius: 10px;
    }
    .genre-box.contact-box {
        padding: 20px;
        /*overflow: scroll;*/
    }
    .scroll-inbox {
        height: 353px;
        overflow-y: scroll;
        overflow-x: hidden;
    }
    .genre-box.contact-box .list-group.clear-list .list-group-item {
        border-color: #fffff0 !important;
    }
    .transparent {
        background-color: rgba(255,255,255,0.8);
        padding: 20px;
        height: 100%;
        /*overflow: scroll;*/
    }
    .check-text {
        width: 30%;
    }

    .body-text,
    .place-text {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        -webkit-text-overflow: ellipsis;
        -o-text-overflow: ellipsis;
    }

    .body-text {
        width: 25%;
        margin-right: 2%;
        text-align: right;
        float: right;
    }
    .place-text {
        width: 15%;
        margin-right: 2%;
        text-align: right;
        float: right;
    }
    .stay-text {
        width: 5%;
        margin-right: 2%;
        text-align: right;
        float: right;
    }
    .time-text {
        width: 6%;
        margin-right: 2%;
        text-align: right;
        float: right;
    }
    .exp-text {
        width: 3%;
        margin-right: 20px;
        text-align: right;
        float: right;
    }
    .search-in {
        height: 430px;
        overflow-y: scroll;
        overflow-x: hidden;
    }
    .search-in2 {
        height: 470px;
        overflow-y: scroll;
        overflow-x: hidden;
    }

    .push-outside {
        overflow: scroll;
    }
    .title-plain {
        max-width: 270px;
        margin-left: -30px;
        margin-bottom: 20px;
        padding: 10px 20px 10px 10px;
        font-size: 17px;
        position: relative;
        background-color: rgba(245,245,245,0.5);
        color: #2f4f4f;
    }
    .title-plain h2 {
        display: inline;
        float: right;
    }
    .title-plain .btn-link {
        margin-top: -10px;
        color: #888888 !important;
    }
    .title-plain .btn-link:hover {
        color: #1ab394 !important;
    }
    .title-plain::before {
        content: '';
        height: 10px;
        width: 100%;
        position: absolute;
        left: 0;
        top: 44px;
        background-color: #a9a9a9;
    }
    @media screen and ( max-width:1199px ) {
        .search-in {
            height: 510px;
        }
        .search-in2 {
            height: 560px;
        }
        .area-box.contact-box,
        .genre-box.contact-box {
            height: 550px;
        }
        .scroll-inbox {
            height: 445px;
        }
    }
    @media screen and ( max-width:767px ) {
        .table-responsive {
            border: none;
        }
        .push-outside {
            height: 500px;
        }
    }
    @media screen and ( max-width:752px ) {
        .phone-display {
            display: block !important;
        }

        .area-box.contact-box, .genre-box.contact-box {
            height: 500px;
        }

        .search-in {
            height: 450px;
        }

        .search-in2 {
            height: 500px;
        }

        .nav-tabs > li > a > span {
            display: none;
        }

        .nav-tabs > li > a {
            padding: 10px 8px 10px 13px;
        }

        span.place-text,
        span.body-text {
            display: none;
        }

        span.place-text,
        span.body-text {
            display: none;
        }

        span.time-text {
            margin-left: -15%;
        }

        span.time-text,
        span.stay-text {
            width: 15%;
        }

        .check-text {
            width: 95%;
        }

        fieldset > div.background-muted > p {
            display: none;
        }
        .genre-push, .area-push {
            height: 100px;
        }
    }
</style>

<div id="tab-1" class="tab-pane active">
    <div class="panel-body">
        <div class="full-height-scroll">
            <h3 class="phone-display p-sm b-r-md bg-muted text-center">
                キーワード検索
            </h3>
            <input id="search1" type="text" class="form-control" value="" placeholder="企画名・建物名・団体名で検索できます。"/>
            <div class="m-t-sm search-in">
                <ul id="search-all" class="list-group clear-list m-t">
                    <?php foreach ($this->data['data'] as $key => $item) : ?>
                        <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                            <span class="exp-text">
                                <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_pt_pid<?php echo $item['pt_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                            </span>
                            <span class="body-text">
                                <?php echo $item['pd_body']; ?>
                            </span>
                            <span class="place-text">
                                <?php echo $item['pp_place']; ?>
                            </span>
                            <span class="stay-text">
                                <?php echo $item['pt_time']; ?> 分
                            </span>
                            <span class="time-text">
                                <?php if ($item['pt_start']) : echo $item['pt_start']; elseif ($item['pt_open']) : echo $item['pt_open']; endif; ?>
                            </span>
                            <span style="display: none;">
                                <?php echo $item['pp_place']," ",$item['pd_label_kana']," ",$item['pd_place_kana']," ",$item['pd_body_kana']; ?>
                            </span>
                            <div class=" check-text">
                                <input type="checkbox" id="1_<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>" class="select-p" name="select-p"> <label for="1_<?php echo $item['pt_pid']; ?>"> <?php echo $item['pd_label']; echo ($item['pt_note']) ? ' <small>'.$item['pt_note'].'</small>' : ''; ?> </label>
                            </div>
                        </li>
                    <?php endforeach; ?>

                </ul>
            </div>
        </div>
    </div>
</div>
<div id="tab-2" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            ジャンル検索
        </h3>
        <div class="full-height-scroll">
            <div class="table-responsive">

                <div class="row push-outside">
                    <?php foreach ($this->data['genre'] as $name => $val) : ?>
                        <div class="col-xs-6 col-md-4">
                            <div id="PushGenre<?php echo $name; ?>" class="genre-push contact-box m-b-sm b-r-lg">
                                <img alt="<?php echo $val[0]['gd_genre_index']; ?>" src="/img/genre/<?php echo $name; ?>.png">
                                <input type="hidden" name="name" value="<?php echo $name; ?>">
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

                <?php foreach ($this->data['genre'] as $name => $val) : ?>
                    <div id="BoxGenre<?php echo $name; ?>" class="genre-box contact-box">
                        <div class="title-plain">
                            <button type="button" class="btn btn-link genre-link">戻る</button>
                            <h2><?php echo $val[0]['gd_genre_index']; ?></h2>
                        </div>
                        <div class="scroll-inbox">
                            <?php foreach ($val as $key2 => $val2) : ?>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <button type="button" class="btn btn-open btn-<?php echo $this->color[$key2%5]; ?> btn-lg btn-outline m-b-md btn-block">
                                        <?php echo $val2['gd_detail_label']; ?>
                                        <input type="hidden" name="btn-val" value="genre<?php echo $val2['gd_pid']; ?>">
                                    </button>
                                    <div class="select-box m-b-md" id="genre<?php echo $val2['gd_pid']; ?>">
                                        <?php if ($val2['data']) : ?>
                                            <ul class="list-group clear-list m-t">
                                            <?php foreach ($val2['data'] as $key => $item) : ?>
                                                <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                                                    <div class=" ">
                                                        <span class="pull-right" style="text-align: right;">
                                                                <button type="button" class="btn btn-info btn-xs btn-modal" data-toggle="modal" data-target="#Modal_pt_pid<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                                        </span>
                                                        <span class="pull-right m-r-xs">
                                                            <?php echo $item['pt_time']; ?> 分
                                                        </span>
                                                <?php if ($item['pt_start']) : ?>
                                                    <span class="pull-right m-r-xs">
                                                                <?php echo $item['pt_start']; ?>
                                                            </span>
                                                    <?php endif; ?>
                                                        <input type="checkbox" id="2_<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>" class="select-p"> <label for="2_<?php echo $item['pt_pid']; ?>"> <?php echo $item['pd_label']; echo ($item['pt_note']) ? ' <small>'.$item['pt_note'].'</small>' : ''; ?> </label>
                                                    </div>
                                                </li>
                                            <?php endforeach; ?>
                                            </ul>
                                        <?php else: ?>
                                            <?php echo '企画はありません。'; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


<div id="tab-3" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            エリア検索
        </h3>
        <div class="row push-outside">
            <?php foreach ($this->data['area'] as $name => $val) : ?>
                <div class="col-xs-12 col-sm-6">
                    <div id="PushArea<?php echo $name; ?>" class="area-push contact-box m-b-sm b-r-md" style="background-image: url(/img/area/<?php echo $name; ?>.png);background-size: cover; cursor: pointer; position: relative;">
                        <input type="hidden" name="name" value="<?php echo $name; ?>">
                        <h3><strong><?php echo $val[0]['bd_p_label1']; ?></strong></h3>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <?php foreach ($this->data['area'] as $name => $val) : ?>
            <div id="BoxArea<?php echo $name; ?>" class="area-box contact-box" style="background-image: url(/img/area/<?php echo $name; ?>.png); background-size: cover;">
                <div class="transparent">
                    <div class="title-plain">
                        <button type="button" class="btn btn-link area-link text-muted">戻る</button>
                        <h2><?php echo $val[0]['bd_p_label1']; ?></h2>
                    </div>
                    <div class="scroll-inbox">
                        <?php foreach ($val as $key2 => $val2) : ?> <!--$key2は数値-->
                            <div class="col-xs-12 col-sm-6 col-md-4">
                                <button type="button" class="btn btn-open btn-<?php echo $this->color[$key2%5]; ?> btn-lg btn-outline m-b-md btn-block">
                                    <?php echo $val2['bd_p_label2']; ?>
                                    <input type="hidden" name="btn-val" value="area<?php echo $val2['bd_pid']; ?>">
                                </button>
                                <div class="select-box m-b-md" id="area<?php echo $val2['bd_pid']; ?>">
                                    <?php if ($val2['data']) : ?>
                                    <ul class="list-group clear-list m-t">
                                        <?php foreach ($val2['data'] as $key => $item) : ?>
                                            <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                                                <div class=" ">
                                                    <span class="pull-right" style="text-align: right;">
                                                    <button type="button" class="btn btn-info btn-xs btn-modal" data-toggle="modal" data-target="#Modal_pt_pid<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                                </span>
                                                    <span class="pull-right m-r-xs">
                                                        <?php echo $item['pt_time']; ?> 分
                                                    </span>
                                                    <?php if ($item['pt_start']) : ?>
                                                    <span class="pull-right m-r-xs">
                                                    <?php echo $item['pt_start']; ?>
                                                </span>
                                                <?php endif; ?>
                                                    <input type="checkbox" id="3_<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>" class="select-p"> <label for="3_<?php echo $item['pt_pid']; ?>"> <?php echo $item['pd_label']; echo ($item['pt_note']) ? ' <small>'.$item['pt_note'].'</small>' : ''; ?> </label>
                                                </div>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                    <?php else : ?>
                                        <?php echo '企画はありません。' ; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; unset($this->info) ?>


</div>
</div>
<div id="tab-4" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            おすすめ企画
        </h3>
        <div class="full-height-scroll">
            <div class="search-in2">
                <ul class="list-group clear-list m-t">
                <?php foreach ($this->data['rec'] as $key => $item) : ?>
                    <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                        <span class="exp-text">
                            <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_pt_pid<?php echo $item['pt_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                                </span>
                        <span class="body-text">
                                    <?php echo $item['pd_body']; ?>
                                </span>
                        <span class="place-text">
                                    <?php echo $item['pp_place']; ?>
                                </span>
                        <span class="stay-text">
                                <?php echo $item['pt_time']; ?> 分
                            </span>
                        <span class="time-text">
                                    <?php echo ($item['pt_start']) ? $item['pt_start'] : '終日'; ?>
                                </span>
                        <div class=" check-text">
                            <input type="checkbox" id="4_<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>" class="select-p"> <label for="4_<?php echo $item['pt_pid']; ?>"> <?php echo $item['pd_label']; echo ($item['pt_note']) ? ' <small>'.$item['pt_note'].'</small>' : ''; ?> </label>
                        </div>
                    </li>
                <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="tab-5" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            ピックアップ企画
        </h3>
        <div class="full-height-scroll">
            <div class="search-in2">
                <ul class="list-group clear-list m-t">
                    <?php foreach ($this->data['pickup'] as $key => $item) : ?>
                        <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                    <span class="exp-text">
                        <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_pt_pid<?php echo $item['pt_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                            </span>
                            <span class="body-text">
                                <?php echo $item['pd_body']; ?>
                            </span>
                            <span class="place-text">
                                <?php echo $item['pp_place']; ?>
                            </span>
                            <span class="stay-text">
                            <?php echo $item['pt_time']; ?> 分
                        </span>
                            <span class="time-text">
                                <?php echo ($item['pt_start']) ? $item['pt_start'] : '終日'; ?>
                            </span>
                            <div class=" check-text">
                                <input type="checkbox" id="5_<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>" class="select-p"> <label for="5_<?php echo $item['pt_pid']; ?>"> <?php echo $item['pd_label']; echo ($item['pt_note']) ? ' <small>'.$item['pt_note'].'</small>' : ''; ?> </label>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="tab-6" class="tab-pane">
    <div class="panel-body">
        <h3 class="phone-display p-sm b-r-md bg-muted text-center">
            学術企画
        </h3>
        <div class="full-height-scroll">
            <div class="search-in2">
                <ul class="list-group clear-list m-t">
                    <?php foreach ($this->data['academic'] as $key => $item) : ?>
                        <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                    <span class="exp-text">
                        <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#Modal_pt_pid<?php echo $item['pt_pid']; ?>"><span class="glyphicon glyphicon-info-sign"></span></button>
                            </span>
                            <span class="body-text">
                                <?php echo $item['pd_body']; ?>
                            </span>
                            <span class="place-text">
                                <?php echo $item['pp_place']; ?>
                            </span>
                            <span class="stay-text">
                            <?php echo $item['pt_time']; ?> 分
                        </span>
                            <span class="time-text">
                                <?php echo ($item['pt_start']) ? $item['pt_start'] : '終日'; ?>
                            </span>
                            <div class=" check-text">
                                <input type="checkbox" id="6_<?php echo $item['pt_pid']; ?>" value="<?php echo $item['pt_pid']; ?>" class="select-p"> <label for="6_<?php echo $item['pt_pid']; ?>"> <?php echo $item['pd_label']; echo ($item['pt_note']) ? ' <small>'.$item['pt_note'].'</small>' : ''; ?> </label>
                            </div>
                        </li>
                    <?php endforeach; unset($this->data); ?>
                </ul>
            </div>
        </div>
    </div>
</div>

<script>
    $('#search-all li').hide();
    $(document).ready(function(){

        $('input#search1').on('keyup', function(){
            Search($(this).val());
        });

        //genre
        // 「id="jQueryBox"」を非表示
        $(".genre-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".genre-push").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $(".genre-push").hide();
            $(this).closest('.push-outside').hide();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#BoxGenre" + key).show();
        });
        $(".genre-link").click(function(e){
            e.stopPropagation();
            $(".genre-push").show();
            $('#tab-2 .push-outside').show();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $(".genre-box").hide();
        });

        //area
        // 「id="jQueryBox"」を非表示
        $(".area-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".area-push").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $(".area-push").hide();
            $(this).closest('.push-outside').hide();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#BoxArea" + key).show();
        });

        $(".area-link").click(function(e){
            e.stopPropagation();
            $(".area-push").show();
            $('#tab-3 .push-outside').show();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $(".area-box").hide();
        });

        // 「id="jQueryBox"」を非表示
        $(".select-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".btn-open").click(function(e){
            e.stopPropagation();
            var key = $(this).find('input[name="btn-val"]').val();
            $("div#" + key).slideToggle('fast');

            // スクロールの速度
            var speed = 400; // ミリ秒
            // 移動先を数値で取得
            var th = $(this).offset().top;
            // スムーススクロール
            var body = $(this).closest('.scroll-inbox');
            /*
            if (key.substr(0,5) == 'genre') {
                var body = $(this).closest('.contact-box');
            } else {
                var body = $(this).closest('.transparent');
            }
            */
            var sh = body.scrollTop();
            var topsize = body.offset().top;
            var pos = th - topsize + sh ;

            body.animate({
                scrollTop: pos
            }, speed, "swing");
        });
        $(".btn-modal").click(function(event) {
            event.stopPropagation();
            $("#Modal_pt_pid" + $(this).val()).modal('show');
        });


        $('input.select-p').change(function() {
            var val = $(this).val();
            console.log(val);
            if ($(this).is(':checked')) {
                console.log("checked");
                $('.select-p[value="' + val + '"]').prop('checked', true);
                $('li#' + val).show();
            } else {
                console.log("unchecked");
                $('.select-p[value="' + val + '"]').prop('checked', false);
                $('li#' + val).hide();
            }
        });
    });

    function Search(keyword) {

        var regExp = new RegExp(keyword);

        $('#search-all').find('li').hide().each(function(){
            var li = $(this);
            $(this).find('label').each(function(){
                if ($(this).text().match(regExp)) {
                    li.show();
                }
            });
            $(this).find('span').each(function(){
                if ($(this).text().match(regExp)) {
                    li.show();
                }
            });
        });
    }
</script>