<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>第90回五月祭 企画展示経路探索</title>

    <link href="/Static_Full_Version/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Static_Full_Version/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/Static_Full_Version/css/animate.css" rel="stylesheet">
    <link href="/Static_Full_Version/css/style.css" rel="stylesheet">

    <!-- common2 -->
    <link href="/css/common2.css" rel="stylesheet">

    <!--checkbox-->
    <link href="/Static_Full_Version/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">

    <!--Clockpicker-->
    <link href="/Static_Full_Version/css/plugins/clockpicker/clockpicker.css" rel="stylesheet">

    <!--select2-->
    <link href="/Static_Full_Version/css/plugins/select2/select2.min.css" rel="stylesheet">

    <!-- chosen -->
    <link href="/Static_Full_Version/css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">

    <!-- iCheck -->
    <link href="/Static_Full_Version/css/plugins/iCheck/custom.css" rel="stylesheet">

    <!-- steps-->
    <link href="/Static_Full_Version/css/plugins/steps/jquery.steps.css" rel="stylesheet">

    <!-- Sweet Alert -->
    <link href="/Static_Full_Version/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">



</head>

<body>



<div id="wrapper">

    <div id="page-wrapper" class="gray-bg" style="margin-left:0px;">
        <div class="row wrapper border-bottom white-bg page-heading" style="height: 120px;background-image: url('/img/may-chan.png');">
            <div class="col-lg-9">
                <a id="jump" href="#id"><div><h1 class="p-xs" style="color: #ff69b4; font-weight: bold;">May Festival 2017 Search Form</h1></div></a>
                <div class="pull-right tooltip-demo" style="background-color:rgba(255,255,255,0.8);"><button type="button" id="ap" class="btn btn-link">工学部応用物理系 五月祭企画展示経路探索サイト</button></div>
            </div>

        </div>
        <div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox" id="id">

                        <div class="ibox-content" style="height: 690px;">

                            <form id="form" action="/index2/result" class="wizard-big">
                                <h1>Date & Time</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-clock-o"> 滞在時間</i></h2>
                                        <p class="text-muted" style="padding-left: 20px;">      滞在日と時間を入力してください。</p>
                                    </div>
                                    <div class="row">
                                        <div class="ibox">
                                            <div class="ibox-content outside b-r-md">
                                                <div class="col-lg-3"></div>
                                                <div class="col-lg-3">
                                                    <div class="contact-box center-version no-borders" style="color: #676a6c;">

                                                        <a >

                                                            <i class="fa fa-calendar fa-5x" style="margin-top: 30px; margin-bottom: 30px;"></i>


                                                            <h3 class="m-b-xs" style="margin-bottom: 30px;"><strong>滞在日</strong></h3>

                                                            <address class="m-t-md">
                                                                <label class="i-checks" id="i-check1"><input type="radio" id="1day" checked="checked" value="1day" name="date"> <i></i> １日目 </label>
                                                                <label class="i-checks" id="i-check2"><input type="radio" id="2day" value="2day" name="date"> <i></i> ２日目 </label>
                                                            </address>

                                                        </a>

                                                    </div>
                                                </div>
                                                <div class="col-lg-3">
                                                    <div class="contact-box center-version no-borders" style="color: #676a6c;">

                                                        <a >

                                                            <i class="fa fa-clock-o fa-5x" style="margin-top: 30px; margin-bottom: 30px;"></i>


                                                            <h3 class="m-b-xs" style="margin-bottom: 30px;"><strong>滞在時間</strong></h3>
                                                            <div id="clock-check">
                                                                <div class="input-group clockpicker" id="clock1">
                                                                    <input class="form-control" name="clock1" id="input-clock1" value="" placeholder="Now">
                                                                    <span class="input-group-addon">
                                                                    <span class="fa fa-clock-o"></span>
                                                                    </span>
                                                                </div>
                                                                <div class="input-group clockpicker" id="clock2">
                                                                    <input type="text" class="form-control" name="clock2" id="input-clock2" value="18:00" >
                                                                    <span class="input-group-addon">
                                                                    <span class="fa fa-clock-o"></span>
                                                                </span>
                                                                </div>
                                                                <span id="clock-check-help1" class="help-block m-b-none text-danger" style="display: none; text-align: left;">滞在終了時刻が開始時刻より早くなっています。</span>
                                                                <span id="clock-check-help2" class="help-block m-b-none text-danger" style="display: none; text-align: left;">五月祭の終了時刻より滞在開始時刻が遅くなっています。</span>
                                                                <span id="clock-check-help3" class="help-block m-b-none text-danger" style="display: none; text-align: left;">五月祭の開始時刻より滞在終了時刻が早くなっています。</span>

                                                            </div>

                                                        </a>

                                                    </div>
                                                </div>
                                                <div class="col-lg-3"></div>

                                            </div>
                                        </div>


                                    </div>

                                </fieldset>
                                <h1>You are here</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-map-marker"> 現在地</i></h2>
                                        <p class="text-muted" style="padding-left: 20px;">現在地を選択してください。</p>
                                    </div>

                                                    <!--
                                                    <p>
                                                        あああ
                                                    </p>
                                                    -->
                                    <div class="ibox">
                                        <div class="ibox-content outside b-r-md">
                                            <select class="select2_demo_1 form-control" style="width:100%;">
                                                <option value="">近くに見える建物の名称,たった今見てきた企画名を記入</option>
                                                <?php foreach ($this->result as $item): ?>
                                                    <option value=""><?php echo $item['fw_name']; ?>　（<small style="text-align:right;"><?php echo $item['fw_area']; ?>　<?php echo $item['fw_place_index']; ?></small>）</option>
                                                <?php endforeach; ?>
                                                <?php foreach ($this->data as $item) : ?>
                                                    <option value=""><?php echo $item['name']."　（".$item['body']."　".$this->contents['list']['area'][$item['area']]."　".$this->contents['list'][$item['area']][$item['place_index']]; ?>）</option>
                                                <?php endforeach; ?>
                                            </select>
                                            <br>
                                            <img src="/img/map1.jpg" alt="本郷キャンパスマップ" style="width:900px; height:600px;" usemap="#shape1" id="shape1">


                                        </div>
                                    </div>

                                </fieldset>

                                <h1>Select Projects</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-eye"> 企画の選択</i></h2>
                                        <p class="text-muted" style="padding-left: 20px;">選択できる企画は５個までです。</p>
                                    </div>
                                    <div class="ibox">
                                        <div class="ibox-content outside b-r-md">

                                            <div class="tabs-container">
                                                <ul class="nav nav-tabs">
                                                    <!--<span class="pull-right small text-muted">1406 Elements</span>-->
                                                    <li class="active"><a data-toggle="tab" href="#tab-1"><i class="fa fa-user"></i> キーワード検索</a></li>
                                                    <li class=""><a data-toggle="tab" href="#tab-2"><i class="fa fa-briefcase"></i> ジャンル検索</a></li>
                                                    <li class=""><a data-toggle="tab" href="#tab-3"><i class="fa fa-briefcase"></i> エリア検索</a></li>
                                                    <li class=""><a data-toggle="tab" href="#tab-4"><i class="fa fa-briefcase"></i> おすすめ・ピックアップ企画</a></li>
                                                    <!--<li class=""><a data-toggle="tab" href="#tab-5"><i class="fa fa-briefcase"></i> これから開演予定の企画検索</a></li>-->
                                                </ul>

                                                <div class="tab-content">
                                                    <div id="tab-1" class="tab-pane active">
                                                        <div class="panel-body">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">
                                                                    <table class="table table-striped table-hover">
                                                                        <tbody>
                                                                        <tr>
                                                                            <span class="help-block m-b-none">行きたい企画の名称,団体名,場所などの文字列を入力してください。</span><br>

                                                                            <select class="select2_demo_1 form-control" id="search_pid" style="width:100%;" multiple="multiple">
                                                                                <option value=""></option>
                                                                                <?php foreach ($this->data as $item) : ?>
                                                                                    <option value="<?php echo $item['pd_pid']; ?>"><?php echo $item['pd_name']."　（".$item['pd_body']."　".$this->contents['list']['area'][$item['area']]."　".$this->contents['list'][$item['area']][$item['place_index']]; ?>）</option>
                                                                                <?php endforeach; ?>
                                                                            </select>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>


                                                    <div id="tab-2" class="tab-pane">
                                                        <div class="panel-body" style="height:480px;overflow: scroll;">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">

                                                                    <div class="row">
                                                                        <div class="col-sm-4">
                                                                            <div id="jQueryPush5" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>展示実演</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox5" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['exhibition'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'exhibition' && $item['genre_detail'] == $key) : ?>
                                                                                                        <div>
                                                                                                        <input type="hidden" name="pid-val" value="<?php echo $item['pid']; ?>">
                                                                                                        <li ><a class="pid-btn" id="pid<?php echo $item['pid']; ?>"><?php echo $item['name']; ?></a></li>
                                                                                                        </div>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-sm-4">

                                                                            <div id="jQueryPush6" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>参加型</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox6" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['join'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'join' && $item['genre_detail'] == $key) : ?>
                                                                                                        <div>
                                                                                                        <input type="hidden" name="pid-val" value="<?php echo $item['pid']; ?>">
                                                                                                        <li><a class="pid-btn" id="pid<?php echo $item['pid']; ?>"><?php echo $item['name']; ?></a></li>
                                                                                                        </div>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-sm-4">

                                                                            <div id="jQueryPush7" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>講演会・討論会</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox7" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['lec_or_critic'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'lec_or_critic' && $item['genre_detail'] == $key) : ?>
                                                                                                        <div>
                                                                                                            <input type="hidden" name="pid-val" value="<?php echo $item['pid']; ?>">
                                                                                                            <li><a class="pid-btn" id="pid<?php echo $item['pid']; ?>"><?php echo $item['name']; ?></a></li>
                                                                                                        </div>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>

                                                                    </div>

                                                                    <div class="row">
                                                                        <div class="col-sm-4">
                                                                            <div id="jQueryPush8" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>パフォーマンス</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox8" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['performance'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'performance' && $item['genre_detail'] == $key) : ?>
                                                                                                        <div>
                                                                                                            <input type="hidden" name="pid-val" value="<?php echo $item['pid']; ?>">
                                                                                                            <li><a class="pid-btn" id="pid<?php echo $item['pid']; ?>"><?php echo $item['name']; ?></a></li>
                                                                                                        </div>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-sm-4">
                                                                            <div id="jQueryPush9" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>音楽</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox9" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['music'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'music' && $item['genre_detail'] == $key) : ?>
                                                                                                        <div>
                                                                                                            <input type="hidden" name="pid-val" value="<?php echo $item['pid']; ?>">
                                                                                                            <li><a class="pid-btn" id="pid<?php echo $item['pid']; ?>"><?php echo $item['name']; ?></a></li>
                                                                                                        </div>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>

                                                                    </div>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>


                                                    <div id="tab-3" class="tab-pane">
                                                        <div class="panel-body">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">
                                                                    <div class="row">
                                                                        <?php foreach ($this->arr_area as $key => $name) : ?>

                                                                            <div class="col-sm-6">
                                                                                <div id="jQueryPush<?php echo $key; ?>" class="contact-box area-push" style="background-image: url(/img/<?php echo $name['name']; ?>.jpg);background-size: cover; cursor: pointer;">
                                                                                    <input type="hidden" name="name" value="<?php echo $key; ?>">
                                                                                    <h3><strong><?php echo $name['label']; ?></strong></h3>
                                                                                </div>

                                                                                <div id="jQueryBox<?php echo $key; ?>" class="contact-box area-box" style="background-image: url(/img/<?php echo $name['name']; ?>.jpg);background-size: cover;">
                                                                                    <input type="hidden" name="name" value="<?php echo $key; ?>">
                                                                                    <?php foreach ($this->area[$name['name']] as $item) : ?>
                                                                                        <ul id="dropmenu" class="dropmenu">
                                                                                            <li><a href="#"><?php echo $item['bd_label']; ?></a>
                                                                                                <ul>
                                                                                                <?php foreach($this->data_area[$name['name']][$item['bd_name']] as $item2) : ?>
                                                                                                    <div>
                                                                                                        <input type="hidden" name="pid-val" value="<?php echo $item2['ps_pid']; ?>">
                                                                                                        <li>
                                                                                                            <!--<button type="button" data-toggle="modal" data-target="#select<?php echo $item2['pd_pid']; ?>"><?php echo $item2['pd_name']; ?></button>
                                                                                                            <div class="modal inmodal fade" id="select<?php echo $item2['pd_pid']; ?>" tabindex="-1" role="dialog"  aria-hidden="true">
                                                                                                                <div class="modal-dialog modal-sm">
                                                                                                                    <div class="modal-content">
                                                                                                                        <div class="modal-header">
                                                                                                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                                                                                                            <h4 class="modal-title">Modal title</h4>
                                                                                                                        </div>
                                                                                                                        <div class="modal-body">
                                                                                                                            <p><strong>Lorem Ipsum is simply dummy</strong> text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown
                                                                                                                                printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
                                                                                                                                remaining essentially unchanged.</p>
                                                                                                                        </div>
                                                                                                                        <div class="modal-footer">
                                                                                                                            <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                                                                                                                            <button type="button" class="btn btn-primary">Save changes</button>
                                                                                                                        </div>
                                                                                                                    </div>
                                                                                                                </div>
                                                                                                            </div>-->

                                                                                                            <a class="pid-btn" id="pid<?php echo $item2['ps_pid']; ?>"><?php echo $item2['pd_name']; ?></a>
                                                                                                        </li>
                                                                                                    </div>
                                                                                                <?php endforeach;?>

                                                                                                </ul>

                                                                                            </li>
                                                                                        </ul>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </div>
                                                                        <?php endforeach; ?>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div id="tab-4" class="tab-pane">
                                                        <div class="panel-body" style="height:540px;overflow: scroll;">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">
                                                                    <table class="table table-hover">
                                                                        <tbody>
                                                                        <?php foreach ($this->data_area as $item) : ?>
                                                                            <?php if ($item['recommend_flg'] == 1) : ?>
                                                                                <tr id="pid<?php echo $item['ps_pid']; ?>">
                                                                                    <input type="hidden" name="pid-val" value="<?php echo $item['ps_pid']; ?>">
                                                                                    <td><a id="pickup<?php echo $item['ps_pid']; ?>" class="client-link pid-btn"><?php echo $item['name']; ?></a></td>
                                                                                    <td><?php echo $item['body']; ?></td>
                                                                                    <!--<td><small class="text-muted"><?php echo $this->contents['list']['area'][$item['area']]; ?></small></td>-->
                                                                                    <td><small class="text-muted"><?php echo $this->contents['list'][$item['area']][$item['place_index']]; ?></small></td>
                                                                                    <!--<td class="contact-type"><i class="fa fa-envelope"> </i></td>
                                                                                    <td class="client-status"><span class="label label-primary"></span></td>-->
                                                                                    <td><button data-toggle="modal" href="#detail<?php echo $item['pid']; ?>" class="btn btn-outline btn-xs btn-warning">detail</button></td>
                                                                                </tr>
                                                                            <?php endif; ?>
                                                                        <?php endforeach; ?>
                                                                        </tbody>
                                                                    </table>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>

                                <h1>Finish</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-rocket"> 確認</i></h2>
                                        <p class="text-muted" style="padding-left: 20px;">      検索前のチェックを行ってください。</p>
                                    </div>
                                    <div class="ibox">
                                        <div class="ibox-content outside b-r-md" style="overflow:hidden;">
                                            <div class="row" style="padding: 15px;">
                                                <div class="col-md-3">
                                                    <div class="panel panel-primary">
                                                        <div class="panel-heading" style="font-size: medium;"><label><i class="fa fa-calendar-o" style="font-size: x-large;"></i> 日にち</label></div>
                                                        <div class="panel-body">
                                                            <div id="jQuery1"><label style="font-weight:normal;">１日目</label></div>
                                                            <div id="jQuery2" style="display: none;"><label style="font-weight:normal;">２日目</label></div>
                                                        </div>
                                                    </div>
                                                    <div class="panel panel-warning">
                                                        <div class="panel-heading" style="font-size: medium;"><label><i class="fa fa-clock-o" style="font-size: x-large;"></i> 滞在予定時刻</label></div>
                                                        <div class="panel-body">
                                                            <label id="clockText1" style="font-weight:normal;">現在時刻</label><label style="font-weight:normal;">〜</label>
                                                            <label id="clockText2" style="font-weight:normal;">16:00</label>
                                                        </div>
                                                    </div>
                                                    <div class="panel panel-info">
                                                        <div class="panel-heading" style="font-size: medium;"><label><i class="fa fa-map-marker" style="font-size: x-large;"></i> 現在地</label></div>
                                                        <div class="panel-body">
                                                            <label id="here" style="weight:normal;">現在時刻</label>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="panel panel-danger">
                                                        <div class="panel-heading" style="font-size: medium;"><label><i class="fa fa-pencil" style="font-size: x-large;"></i> 選択した企画</label></div>
                                                        <div class="panel-body" style="height:320px;">
                                                        <table class="table table-hover">
                                                            <tbody>
                                                            <?php foreach($this->data_all as $item) : ?>
                                                                <tr id="form_pid<?php echo $item['ps_pid']; ?>" style="display:none; ">
                                                                    <td><?php echo $item['pd_name']; ?></td>
                                                                    <td><?php echo $item['pd_body']; ?></td>
                                                                    <td><?php echo $this->contents['list']['area'][$item['area']]; ?></td>
                                                                    <td><?php echo $this->contents['list'][$item['area']][$item['place_index']]; ?></td>
                                                                    <input type="hidden" id="hidden-input" name="input<?php echo $item['ps_pid']; ?>" value="">
                                                                </tr>
                                                            <?php endforeach; ?>
                                                            </tbody>
                                                        </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>



                                        </div>
                                    </div>

                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
            <a href="/index2/algorithm"><div id="may-chan"></div></a>
            <div id="comment"></div>
        </div>
        <div class="footer">
        <!--<div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>-->
            <div>
                <strong>Applied Physics ,University of Tokyo</strong> 東京大学工学部応用物理系 &copy; 2017
            </div>
        </div>

    </div>
</div>


<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<!-- Mainly scripts -->
<script src="/Static_Full_Version/js/jquery-3.1.1.min.js"></script>
<script src="/Static_Full_Version/js/bootstrap.min.js"></script>
<script src="/Static_Full_Version/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="/Static_Full_Version/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="/Static_Full_Version/js/inspinia.js"></script>
<script src="/Static_Full_Version/js/plugins/pace/pace.min.js"></script>

<!-- Steps -->
<script src="/Static_Full_Version/js/plugins/steps/jquery.steps.min.js"></script>

<!-- Jquery Validate -->
<script src="/Static_Full_Version/js/plugins/validate/jquery.validate.min.js"></script>

<!-- iCheck -->
<script src="/Static_Full_Version/js/plugins/iCheck/icheck.min.js"></script>

<!-- Clock picker -->
<script src="/Static_Full_Version/js/plugins/clockpicker/clockpicker.js"></script>

<!-- Select2 -->
<script src="/Static_Full_Version/js/plugins/select2/select2.full.min.js"></script>

<!-- Chosen -->
<script src="/Static_Full_Version/js/plugins/chosen/chosen.jquery.js"></script>

<!-- Sweet alert -->
<script src="/Static_Full_Version/js/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    $('.chosen-select').chosen({width: "15%"});

    $(document).ready(function(){
        $("#wizard").steps();
        $("#form").steps({
            bodyTag: "fieldset",
            onStepChanging: function (event, currentIndex, newIndex)
            {
                // Always allow going backward even if the current step contains invalid fields!
                if (currentIndex > newIndex)
                {
                    return true;
                }

                // Forbid suppressing "Warning" step if the user is to young
                /*
                if (newIndex === 3 && Number($("#age").val()) < 18)
                {
                    return false;
                }
                */
                var form = $(this);

                // Clean up if user went backward before
                if (currentIndex < newIndex)
                {
                    // To remove error styles
                    $(".body:eq(" + newIndex + ") label.error", form).remove();
                    $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                }

                // Disable validation on fields that are disabled or hidden.
                form.validate().settings.ignore = ":disabled,:hidden";

                // Start validation; Prevent going forward if false
                return form.valid();
            },
            onStepChanged: function (event, currentIndex, priorIndex)
            {
                // Suppress (skip) "Warning" step if the user is old enough.
                if (currentIndex === 2 && Number($("#age").val()) >= 18)
                {
                    $(this).steps("next");
                }

                /*
                // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                if (currentIndex === 2 && priorIndex === 3)
                {
                    $(this).steps("previous");
                }
                */
            },
            onFinishing: function (event, currentIndex)
            {
                var form = $(this);

                var j = 0;

                var search = new Array();
                for(i=1;i<600;i++) {
                    name = "input" + i;
                    hidden = $('[name=' + name + ']').val();
                    if (hidden) {
                        search[j] = hidden;
                        j++;
                    }
                    console.log(name);
                    console.log(hidden);
                }

                // Disable validation on fields that are disabled.
                // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                form.validate().settings.ignore = ":disabled";

                // Start validation; Prevent form submission if false

                if (j  == 0) {
                    swal({
                        title: "企画が選択されてません",
                        text: "検索するには、企画を１つ以上選択してください",
                        type: "warning",
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "OK",
                        closeOnConfirm: false
                    });
                } else if (j > 10) {
                    swal({
                        title: "選択された企画が多すぎます",
                        text: "選択する企画は１０個以下にしてください",
                        type: "warning",
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "OK",
                        closeOnConfirm: false
                    });
                } else {
                    $.ajax({
                        url: "/index2/search",
                        type: "POST",
                        data: {
                            search : search
                        },
                        success: function(arr) {
                            console.log("aaa");
                            console.log(arr);
                            window.location.href = "/index2/result";

                        },
                        error:function() {
                            alert('問題がありました。');
                        }
                    });
                }

            },
            onFinished: function (event, currentIndex)
            {
                window.location.href = '/result';
                var form = $(this);

                // Submit form input
                form.submit();
            }
        }).validate({
            errorPlacement: function (error, element)
            {
                element.before(error);
            },
            rules: {
                confirm: {
                    equalTo: "#password"
                }
            }
        });

        //iCheck
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
        $('input').on('ifChecked', function(event){
            $("#jQuery1").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQuery2").toggle();
        });

        //clockpicker
        var input = $('#clock1').clockpicker({
            placement: 'bottom',
            align: 'left',
            //autoclose: true,
            'default': 'now'
        });
        $('#clock2').clockpicker({
            placement: 'bottom',
            align: 'left',
            //autoclose: true,
        });

        $('#input-clock1').change(function() {
            if ($('#input-clock1').val()) {
                $("#clockText1").text($('#input-clock1').val());
            }
            a = $('#input-clock1').val();
            b = $('#input-clock2').val();
            c = parseInt(a.substr(0,2)*60) + parseInt(a.substr(3,2));
            d = parseInt(b.substr(0,2)*60 )+ parseInt(b.substr(3,2));

            console.log(parseInt(c) >= 1080);
            if (parseInt(c) >= parseInt(d)) {
                $('#clock-check').addClass('has-error');
                $('#clock-check-help1').show();
            } else {
                $('#clock-check-help1').hide();
            }
            if (parseInt(c) >= 1080) {
                $('#clock-check').addClass('has-error');
                $('#clock-check-help2').show();
            } else {
                $('#clock-check-help2').hide();
            }
            if (parseInt(c) < parseInt(d) && parseInt(c) < 1080 && parseInt(d) > 540) {
                $('#clock-check').removeClass('has-error');
            }
        });
        $('#input-clock2').change(function() {
            $("#clockText2").text($('#input-clock2').val());
            if ($('#input-clock1').val() > $('#input-clock2').val()) {
                $('#clock-check').addClass('has-error');
            }
            a = $('#input-clock1').val();
            b = $('#input-clock2').val();
            c = parseInt(a.substr(0,2)*60) + parseInt(a.substr(3,2));
            d = parseInt(b.substr(0,2)*60 )+ parseInt(b.substr(3,2));
            console.log(c);
            console.log(d);

            if (parseInt(c) >= parseInt(d)) {
                $('#clock-check').addClass('has-error');
                $('#clock-check-help1').show();
            } else {
                $('#clock-check-help1').hide();
            }
            if (parseInt(d) <= 540) {
                $('#clock-check').addClass('has-error');
                $('#clock-check-help3').show();
            } else {
                $('#clock-check-help3').hide();
            }
            if (parseInt(c) < parseInt(d) && parseInt(d) > 540 && parseInt(c) < 1080) {
                $('#clock-check').removeClass('has-error');
            }

        });

        //select2
        $(".select2_demo_1").select2();
        $(".select2_demo_2").select2();
        $(".select2_demo_3").select2({
            placeholder: "Select a state",
            allowClear: true
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $(".area-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".area-push").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $("#jQueryPush" + key).toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox" + key).toggle();
        });

        $(".area-box").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $("#jQueryPush" + key).toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox" + key).toggle();
        });
    });


    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox5").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush5").click(function(){
            $("#jQueryPush5").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox5").toggle();
        });

        $("#jQueryBox5").click(function(){
            $("#jQueryPush5").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox5").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox6").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush6").click(function(){
            $("#jQueryPush6").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox6").toggle();
        });

        $("#jQueryBox6").click(function(){
            $("#jQueryPush6").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox6").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox7").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush7").click(function(){
            $("#jQueryPush7").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox7").toggle();
        });

        $("#jQueryBox7").click(function(){
            $("#jQueryPush7").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox7").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox8").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush8").click(function(){
            $("#jQueryPush8").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox8").toggle();
        });

        $("#jQueryBox8").click(function(){
            $("#jQueryPush8").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox8").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox9").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush9").click(function(){
            $("#jQueryPush9").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox9").toggle();
        });

        $("#jQueryBox9").click(function(){
            $("#jQueryPush9").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox9").toggle();
        });
    });



    /* 企画の項目を選んで表示 */

    $(function() {


        //キーワード検索
        $("#search_pid").on("select2:select", function () {
            pid = $(this).val();

            $.each(pid,
                function(index, elem) {
                    val = "#form_pid" + elem;
                    $(val).show();

                    val1 = "input" + elem;
                    $('[name=' + val1 + ']').val(elem);

                    val2 = 'a#pid'+elem;
                    console.log(val2);
                    $(val2).addClass("highlight",1000);
                    //$("#pid28 a").toggleClass("highlight",1000);

                    val3 = 'a#pickup' + elem;
                    $(val3).addClass("highlight",1000);

                }
            );
        });

        //キーワード検索　消す
        $("#search_pid").on("select2:unselect", function (e) {

            val = "#form_pid" + e.params.data.id;
            $(val).hide();

            val1 = "input" + e.params.data.id;
            console.log(val1);
            $('[name=' + val1 + ']').val("");

            $('[name=val]').val();

            val2 = 'a#pid'+e.params.data.id;
            console.log(val2);
            $(val2).removeClass("highlight",1000);

            val3 = 'a#pickup' + e.params.data.id;
            $(val3).removeClass("highlight",1000);


        });

        $("#dropmenu").click(function (e) {
            e.stopPropagation(); // 追加
        });
        $("#dropmenu li").click(function (e) {
            e.stopPropagation(); // 追加
        });
    });

    $(function() {
        $("a.pid-btn").click(function () {
            var id = $(this).parent().parent().find('input[name="pid-val"]').val();
            console.log(id);
            var name1 = '#form_pid' + id;
            $(name1).toggle();
            $(this).toggleClass("highlight", 1000);
            var name2 = '[name="input' + id + '"]';
            var now_val = $(name2).val();
            console.log(now_val);
            if (now_val) {
                $(name2).val("");
            } else {
                $(name2).val(id);
            }
            var name3  = "a#pickup" + id;
            $(name3).toggleClass("highlight", 1000);
        });
    });

    $(document).ready(function () {

        $('#ap').click(function (e) {
            e.stopPropagation();
            swal({
                title: "工学部応用物理系ってなあに？",
                text: "You will not be able to recover this imaginary file!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "詳細が知りたい！",
                closeOnConfirm: false,
                allowOutsideClick: true,
            }, function () {
                window.location.href = "";
            });
        });
    });

    //ページ内ゆっくり遷移

    $(function(){
        $('a[href="#id"]').click(function(){
            var speed = 500;
            var href= $(this).attr("href");
            var target = $('#id');
            var position = target.offset().top;
            $("html, body").animate({scrollTop:position}, speed, "swing");
            return false;
        });
    });

    //めいちゃんhover

    $(function(){
        $('div#may-chan').hover(
            function() {
                $('div#comment').show("normal");
            }, function() {
                $('div#comment').hide("normal");
            }
        );
    });


</script>

</body>

</html>

