<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>第90回五月祭 企画展示経路探索</title>

    <link href="/Static_Full_Version/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Static_Full_Version/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/Static_Full_Version/css/animate.css" rel="stylesheet">
    <link href="/Static_Full_Version/css/style.css" rel="stylesheet">

    <!-- common2 -->
    <link href="/css/common2.css" rel="stylesheet">

    <!--checkbox-->
    <link href="/Static_Full_Version/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">

    <!--Clockpicker-->
    <link href="/Static_Full_Version/css/plugins/clockpicker/clockpicker.css" rel="stylesheet">

    <!--select2-->
    <link href="/Static_Full_Version/css/plugins/select2/select2.min.css" rel="stylesheet">

    <!-- chosen -->
    <link href="/Static_Full_Version/css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">

    <!-- iCheck -->
    <link href="/Static_Full_Version/css/plugins/iCheck/custom.css" rel="stylesheet">

    <!-- steps-->
    <link href="/Static_Full_Version/css/plugins/steps/jquery.steps.css" rel="stylesheet">

    <!-- Sweet Alert -->
    <link href="/Static_Full_Version/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">



</head>

<body>



<div id="wrapper">

    <div id="page-wrapper" class="gray-bg" style="margin-left:0px;">
        <div class="row wrapper border-bottom white-bg page-heading" style="height: 120px;background-image: url('/img/may-chan.png');">
            <div class="col-lg-9">
                <a href="#id"><div style="background-color:rgba(255,255,255,0.8);"><h1 class="p-xs" style="color: #ff69b4; font-weight: bold;">May Festival 2017 Search Form</h1></div></a>
                <div class="pull-right tooltip-demo" style="background-color:rgba(255,255,255,0.8);"><button type="button" id="ap" class="btn btn-link">工学部応用物理系 五月祭企画展示経路探索サイト</button></div>
            </div>

        </div>
        <div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox" id="id">

                        <div class="ibox-content" style="height: 690px;">

                            <form id="form" action="#" class="wizard-big">
                                <h1>Date & Time</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-clock-o"> 滞在時間</i></h2>
                                    </div>
                                    <div class="row">
                                        <div class="ibox">
                                            <div class="ibox-content outside b-r-md">
                                                <div class="col-lg-8">
                                                    <div class="form-group"><label class="col-sm-2 control-label">日にち</label>
                                                        <div class="col-sm-10">
                                                            <label class="radio-inline i-checks" id="i-check1"><input type="radio" id="1day" checked="checked" value="1day" name="date"> <i></i> １日目 </label>
                                                            <label class="radio-inline i-checks" id="i-check2"><input type="radio" id="2day" value="2day" name="date"> <i></i> ２日目 </label>
                                                        </div>
                                                    </div>

                                                    <div class="form-group"><label class="col-sm-2 control-label">滞在予定時間</label>
                                                        <div class="col-sm-4">

                                                            <div class="input-group clockpicker" id="clock1">
                                                                <input class="form-control" name="clock1" id="input-clock1" value="" placeholder="Now">
                                                                <span class="input-group-addon">
                                                            <span class="fa fa-clock-o"></span>
                                                        </span>
                                                            </div>
                                                        </div>
                                                        <div class="col-sm-1" style="padding-top:10px;">〜</div>
                                                        <div class="col-sm-4">
                                                            <div class="input-group clockpicker" id="clock2">
                                                                <input type="text" class="form-control" name="clock2" id="input-clock2" value="16:00" >
                                                                <span class="input-group-addon">
                                                            <span class="fa fa-clock-o"></span>
                                                        </span>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>


                                    </div>

                                </fieldset>
                                <h1>You are here</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-map-marker"> 現在地</i></h2>
                                    </div>

                                                    <!--
                                                    <p>
                                                        あああ
                                                    </p>
                                                    -->
                                    <div class="ibox">
                                        <div class="ibox-content outside b-r-md">
                                            <select class="select2_demo_1 form-control" style="width:100%;">
                                                <option value="">近くに見える建物の名称,たった今見てきた企画名を記入</option>
                                                <?php foreach ($this->result as $item): ?>
                                                    <option value=""><?php echo $item['fw_name']; ?>　（<small style="text-align:right;"><?php echo $item['fw_area']; ?>　<?php echo $item['fw_place_index']; ?></small>）</option>
                                                <?php endforeach; ?>
                                                <?php foreach ($this->data as $item) : ?>
                                                    <option value=""><?php echo $item['name']."　（".$item['body']."　".$this->contents['list']['area'][$item['area']]."　".$this->contents['list'][$item['area']][$item['place_index']]; ?>）</option>
                                                <?php endforeach; ?>
                                            </select>
                                            <br>
                                            <img src="/img/map1.jpg" alt="本郷キャンパスマップ" style="width:900px; height:600px;" usemap="#shape1" id="shape1">


                                        </div>
                                    </div>

                                </fieldset>

                                <h1>Select Projects</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-eye"> 企画の選択</i></h2>
                                        <p class="text-muted">選択できる企画は５個までです。</p>
                                    </div>
                                    <div class="ibox">
                                        <div class="ibox-content outside b-r-md">

                                            <div class="tabs-container">
                                                <ul class="nav nav-tabs">
                                                    <!--<span class="pull-right small text-muted">1406 Elements</span>-->
                                                    <li class="active"><a data-toggle="tab" href="#tab-1"><i class="fa fa-user"></i> キーワード検索</a></li>
                                                    <li class=""><a data-toggle="tab" href="#tab-2"><i class="fa fa-briefcase"></i> ジャンル検索</a></li>
                                                    <li class=""><a data-toggle="tab" href="#tab-3"><i class="fa fa-briefcase"></i> エリア検索</a></li>
                                                    <li class=""><a data-toggle="tab" href="#tab-4"><i class="fa fa-briefcase"></i> おすすめ・ピックアップ企画</a></li>
                                                    <!--<li class=""><a data-toggle="tab" href="#tab-5"><i class="fa fa-briefcase"></i> これから開演予定の企画検索</a></li>-->
                                                </ul>

                                                <div class="tab-content">
                                                    <div id="tab-1" class="tab-pane active">
                                                        <div class="panel-body">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">
                                                                    <table class="table table-striped table-hover">
                                                                        <tbody>
                                                                        <tr>
                                                                            <select class="select2_demo_1 form-control" id="search_pid" style="width:100%;" multiple="multiple">
                                                                                <option value="">行きたい企画の名称,団体名,場所などの文字列を入力してください</option>
                                                                                <?php foreach ($this->data as $item) : ?>
                                                                                    <option value="<?php echo $item['pid']; ?>"><?php echo $item['name']."　（".$item['body']."　".$this->contents['list']['area'][$item['area']]."　".$this->contents['list'][$item['area']][$item['place_index']]; ?>）</option>
                                                                                <?php endforeach; ?>
                                                                            </select>
                                                                        </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>


                                                    <div id="tab-2" class="tab-pane">
                                                        <div class="panel-body" style="height:540px;overflow: scroll;">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">

                                                                    <div class="row">
                                                                        <div class="col-sm-6">
                                                                            <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <h3><strong>展示実演</strong></h3>
                                                                            </div>
                                                                            <div class="contact-box">
                                                                                <?php foreach ($this->contents['list']['exhibition'] as $key => $place) : ?>

                                                                                <ul id="dropmenu" class="dropmenu">
                                                                                    <li><a href="#"><?php echo $place; ?></a>
                                                                                        <?php foreach($this->data as $item) : ?>
                                                                                            <?php if ($item['area'] == 'exhibition' && $item['place_index'] == $key) : ?>
                                                                                                <ul>
                                                                                                    <li><a href="#"><?php echo $item['name']; ?></a></li>

                                                                                                </ul>
                                                                                            <?php endif; ?>
                                                                                        <?php endforeach; ?>
                                                                                    </li>
                                                                                </ul>
                                                                                <?php endforeach; ?>

                                                                                <!--
                                                                                <select class="select2_demo_1 form-control" style="width:100%;">
                                                                                    <option value="">近くに見える建物の名称,たった今見てきた企画名を記入</option>
                                                                                    <?php foreach ($this->contents['list']['exhibition'] as $key => $place) : ?>
                                                                                        <option value=""><?php echo $item['fw_name']; ?>　（<small style="text-align:right;"><?php echo $item['fw_area']; ?>　<?php echo $item['fw_place_index']; ?></small>）</option>
                                                                                    <?php endforeach; ?>
                                                                                </select>


                                                                                <?php foreach ($this->contents['list']['exhibition'] as $key => $place) : ?>
                                                                                    <div class="ibox-title">
                                                                                        <h5><?php echo $place; ?></h5>
                                                                                        <div class="ibox-tools">
                                                                                            <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                            </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                        <ul class="list-group">
                                                                                            <?php foreach($this->data as $item) : ?>
                                                                                                <?php if ($item['area'] == 'exhibition' && $item['place_index'] == $key) : ?>
                                                                                                    <li class="list-group-item">
                                                                                                        <?php echo $item['name']; ?></li>
                                                                                                <?php endif; ?>
                                                                                            <?php endforeach; ?>
                                                                                        </ul>
                                                                                    </div>
                                                                                <?php endforeach; ?>
                                                                                -->
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-sm-6">
                                                                            <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <h3><strong>参加型</strong></h3>
                                                                                <br><br><br><br><br>
                                                                                <div class="clearfix"></div>
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <div class="ibox-title">
                                                                                        <h5>Select</h5>
                                                                                        <div class="ibox-tools">
                                                                                            <a class="collapse-link">
                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                            </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="ibox-content" style="display: none;">
                                                                                        <ul class="list-group">
                                                                                            <div class="ibox float-e-margins border-bottom">
                                                                                                <?php foreach ($this->contents['list']['join'] as $key => $place) : ?>
                                                                                                    <div class="ibox-title">
                                                                                                        <h5><?php echo $place; ?></h5>
                                                                                                        <div class="ibox-tools">
                                                                                                            <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                                            </a>
                                                                                                        </div>
                                                                                                    </div>
                                                                                                    <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                        <ul class="list-group">
                                                                                                            <?php foreach($this->data as $item) : ?>
                                                                                                                <?php if ($item['genre'] == 'join' && $item['genre_detail'] == $key) : ?>
                                                                                                                    <li class="list-group-item">
                                                                                                                        <?php echo $item['name']; ?></li>
                                                                                                                <?php endif; ?>
                                                                                                            <?php endforeach; ?>
                                                                                                        </ul>
                                                                                                    </div>
                                                                                                <?php endforeach; ?>
                                                                                            </div>
                                                                                        </ul>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>

                                                                    </div>

                                                                    <div class="row">
                                                                        <div class="col-sm-6">
                                                                            <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <h3><strong>講演会・評論会</strong></h3>
                                                                                <br><br><br><br><br>
                                                                                <div class="clearfix"></div>
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <div class="ibox-title">
                                                                                        <h5>Select</h5>
                                                                                        <div class="ibox-tools">
                                                                                            <a class="collapse-link">
                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                            </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="ibox-content" style="display: none;">
                                                                                        <ul class="list-group">
                                                                                            <div class="ibox float-e-margins border-bottom">
                                                                                                <?php foreach ($this->contents['list']['lec_or_critic'] as $key => $place) : ?>
                                                                                                    <div class="ibox-title">
                                                                                                        <h5><?php echo $place; ?></h5>
                                                                                                        <div class="ibox-tools">
                                                                                                            <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                                            </a>
                                                                                                        </div>
                                                                                                    </div>
                                                                                                    <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                        <ul class="list-group">
                                                                                                            <?php foreach($this->data as $item) : ?>
                                                                                                                <?php if ($item['genre'] == 'lec_or_critic' && $item['genre_detail'] == $key) : ?>
                                                                                                                    <li class="list-group-item">
                                                                                                                        <?php echo $item['name']; ?></li>
                                                                                                                <?php endif; ?>
                                                                                                            <?php endforeach; ?>
                                                                                                        </ul>
                                                                                                    </div>
                                                                                                <?php endforeach; ?>
                                                                                            </div>
                                                                                        </ul>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>

                                                                        <div class="col-sm-6">
                                                                            <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <h3><strong>パフォーマンス</strong></h3>
                                                                                <br><br><br><br><br>
                                                                                <div class="clearfix"></div>
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <div class="ibox-title">
                                                                                        <h5>Select</h5>
                                                                                        <div class="ibox-tools">
                                                                                            <a class="collapse-link">
                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                            </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="ibox-content" style="display: none;">
                                                                                        <ul class="list-group">
                                                                                            <div class="ibox float-e-margins border-bottom">
                                                                                                <?php foreach ($this->contents['list']['performance'] as $key => $place) : ?>
                                                                                                    <div class="ibox-title">
                                                                                                        <h5><?php echo $place; ?></h5>
                                                                                                        <div class="ibox-tools">
                                                                                                            <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                                            </a>
                                                                                                        </div>
                                                                                                    </div>
                                                                                                    <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                        <ul class="list-group">
                                                                                                            <?php foreach($this->data as $item) : ?>
                                                                                                                <?php if ($item['genre'] == 'performance' && $item['genre_detail'] == $key) : ?>
                                                                                                                    <li class="list-group-item">
                                                                                                                        <?php echo $item['name']; ?></li>
                                                                                                                <?php endif; ?>
                                                                                                            <?php endforeach; ?>
                                                                                                        </ul>
                                                                                                    </div>
                                                                                                <?php endforeach; ?>
                                                                                            </div>
                                                                                        </ul>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>

                                                                    </div>

                                                                    <div class="row">
                                                                        <div class="col-sm-6">
                                                                            <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <h3><strong>音楽</strong></h3>
                                                                                <br><br><br><br><br>
                                                                                <div class="clearfix"></div>
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <div class="ibox-title">
                                                                                        <h5>Select</h5>
                                                                                        <div class="ibox-tools">
                                                                                            <a class="collapse-link">
                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                            </a>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="ibox-content" style="display: none;">
                                                                                        <ul class="list-group">
                                                                                            <div class="ibox float-e-margins border-bottom">
                                                                                                <?php foreach ($this->contents['list']['music'] as $key => $place) : ?>
                                                                                                    <div class="ibox-title">
                                                                                                        <h5><?php echo $place; ?></h5>
                                                                                                        <div class="ibox-tools">
                                                                                                            <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                                <i class="fa fa-chevron-up"></i>
                                                                                                            </a>
                                                                                                        </div>
                                                                                                    </div>
                                                                                                    <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                        <ul class="list-group">
                                                                                                            <?php foreach($this->data as $item) : ?>
                                                                                                                <?php if ($item['genre'] == 'music' && $item['genre_detail'] == $key) : ?>
                                                                                                                    <li class="list-group-item">
                                                                                                                        <?php echo $item['name']; ?></li>
                                                                                                                <?php endif; ?>
                                                                                                            <?php endforeach; ?>
                                                                                                        </ul>
                                                                                                    </div>
                                                                                                <?php endforeach; ?>
                                                                                            </div>
                                                                                        </ul>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>

                                                                    </div>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>


                                                    <div id="tab-3" class="tab-pane">
                                                        <div class="panel-body">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">
                                                                    <div class="row">
                                                                        <div class="col-sm-6">
                                                                            <div id="jQueryPush1" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>農学部エリア</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox1" class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['no_dept'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'no_dept' && $item['place_index'] == $key) : ?>

                                                                                                        <li id="pid<?php echo $item['pid']; ?>"><a><?php echo $item['name']; ?></a></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-6">

                                                                            <div id="jQueryPush2" class="contact-box" style="background-image: url(/img/kougaku.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>工学部エリア</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox2" class="contact-box" style="background-image: url(/img/kougaku.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['ko_dept'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'ko_dept' && $item['place_index'] == $key) : ?>

                                                                                                        <li id="pid<?php echo $item['pid']; ?>"><a><?php echo $item['name']; ?></a></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="col-sm-6">
                                                                            <div id="jQueryPush3" class="contact-box" style="background-image: url(/img/yasuko.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>安田講堂エリア</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox3" class="contact-box" style="background-image: url(/img/yasuko.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['yasuko'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'yasuko' && $item['place_index'] == $key) : ?>

                                                                                                        <li id="pid<?php echo $item['pid']; ?>"><a><?php echo $item['name']; ?></a></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-sm-6">
                                                                            <div id="jQueryPush4" class="contact-box" style="background-image: url(/img/akamon.jpg);background-size: cover; cursor: pointer;">
                                                                                <h3><strong>赤門エリア</strong></h3>
                                                                            </div>

                                                                            <div id="jQueryBox4" class="contact-box" style="background-image: url(/img/akamon.jpg);background-size: cover;">
                                                                                <?php foreach ($this->contents['list']['akamon'] as $key => $place) : ?>
                                                                                    <ul id="dropmenu" class="dropmenu">
                                                                                        <li><a href="#"><?php echo $place; ?></a>
                                                                                            <ul>
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'akamon' && $item['place_index'] == $key) : ?>

                                                                                                        <li id="pid<?php echo $item['pid']; ?>"><a><?php echo $item['name']; ?></a></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach;?>

                                                                                            </ul>

                                                                                        </li>
                                                                                    </ul>
                                                                                <?php endforeach; ?>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div id="tab-4" class="tab-pane">
                                                        <div class="panel-body" style="height:540px;overflow: scroll;">
                                                            <div class="full-height-scroll">
                                                                <div class="table-responsive">
                                                                    <table class="table table-hover">
                                                                        <tbody>
                                                                        <?php foreach ($this->data as $item) : ?>
                                                                            <?php if ($item['recommend_flg'] == 1) : ?>
                                                                                <tr id="pid<?php echo $item['pid']; ?>">
                                                                                    <td><a id="<?php echo $item['pid']; ?>" class="client-link"><?php echo $item['name']; ?></a></td>
                                                                                    <td><?php echo $item['body']; ?></td>
                                                                                    <!--<td><small class="text-muted"><?php echo $this->contents['list']['area'][$item['area']]; ?></small></td>-->
                                                                                    <td><small class="text-muted"><?php echo $this->contents['list'][$item['area']][$item['place_index']]; ?></small></td>
                                                                                    <!--<td class="contact-type"><i class="fa fa-envelope"> </i></td>
                                                                                    <td class="client-status"><span class="label label-primary"></span></td>-->
                                                                                    <td><button data-toggle="" href="" class="btn btn-outline btn-xs btn-warning">detail</button></td>
                                                                                </tr>
                                                                            <?php endif; ?>
                                                                        <?php endforeach; ?>
                                                                        </tbody>
                                                                    </table>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>

                                <h1>Finish</h1>
                                <fieldset>
                                    <div class="p-sm b-r-md background-muted">
                                        <h2><i class="fa fa-rocket"> 確認</i></h2>
                                    </div>
                                    <div class="ibox">
                                        <div class="ibox-content outside b-r-md">
                                            <div class="form-group"><label class="col-sm-2 control-label">日にち</label>
                                                <div class="col-sm-10">
                                                    <div id="jQuery1"><label style="font-weight:normal;">１日目</label></div>
                                                    <div id="jQuery2" style="display: none;"><label style="font-weight:normal;">２日目</label></div>
                                                </div>
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">滞在予定時刻</label>
                                                <div class="col-sm-10">
                                                    <label id="clockText1" style="font-weight:normal;">現在時刻</label><label style="font-weight:normal;">〜</label>
                                                    <label id="clockText2" style="font-weight:normal;">16:00</label>
                                                </div>
                                            </div>
                                            <div class="form-group"><label class="col-sm-2 control-label">選択した企画</label>
                                                <div class="col-sm-10">
                                                    <table class="table table-hover">

                                                        <tbody>

                                                        <?php foreach($this->data as $item) : ?>
                                                            <tr id="form_pid<?php echo $item['pid']; ?>" style="display:none; ">
                                                            <td><?php echo $item['name']; ?></td>
                                                            <td><?php echo $item['body']; ?></td>
                                                            <td><?php echo $this->contents['list']['area'][$item['area']]; ?></td>
                                                            <td><?php echo $this->contents['list'][$item['area']][$item['place_index']]; ?></td>
                                                            <td><input type="hidden" id="hidden-input" name="input<?php echo $item['pid']; ?>" value=""></td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="footer">
        <!--<div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>-->
            <div>
                <strong>Applied Physics ,University of Tokyo</strong> 東京大学工学部応用物理系 &copy; 2017
            </div>
        </div>

    </div>
</div>


<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<!-- Mainly scripts -->
<script src="/Static_Full_Version/js/jquery-3.1.1.min.js"></script>
<script src="/Static_Full_Version/js/bootstrap.min.js"></script>
<script src="/Static_Full_Version/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="/Static_Full_Version/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="/Static_Full_Version/js/inspinia.js"></script>
<script src="/Static_Full_Version/js/plugins/pace/pace.min.js"></script>

<!-- Steps -->
<script src="/Static_Full_Version/js/plugins/steps/jquery.steps.min.js"></script>

<!-- Jquery Validate -->
<script src="/Static_Full_Version/js/plugins/validate/jquery.validate.min.js"></script>

<!-- iCheck -->
<script src="/Static_Full_Version/js/plugins/iCheck/icheck.min.js"></script>

<!-- Clock picker -->
<script src="/Static_Full_Version/js/plugins/clockpicker/clockpicker.js"></script>

<!-- Select2 -->
<script src="/Static_Full_Version/js/plugins/select2/select2.full.min.js"></script>

<!-- Chosen -->
<script src="/Static_Full_Version/js/plugins/chosen/chosen.jquery.js"></script>

<!-- Sweet alert -->
<script src="/Static_Full_Version/js/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    $('.chosen-select').chosen({width: "15%"});

    $(document).ready(function(){
        $("#wizard").steps();
        $("#form").steps({
            bodyTag: "fieldset",
            onStepChanging: function (event, currentIndex, newIndex)
            {
                // Always allow going backward even if the current step contains invalid fields!
                if (currentIndex > newIndex)
                {
                    return true;
                }

                // Forbid suppressing "Warning" step if the user is to young
                /*
                if (newIndex === 3 && Number($("#age").val()) < 18)
                {
                    return false;
                }
                */
                var form = $(this);

                // Clean up if user went backward before
                if (currentIndex < newIndex)
                {
                    // To remove error styles
                    $(".body:eq(" + newIndex + ") label.error", form).remove();
                    $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                }

                // Disable validation on fields that are disabled or hidden.
                form.validate().settings.ignore = ":disabled,:hidden";

                // Start validation; Prevent going forward if false
                return form.valid();
            },
            onStepChanged: function (event, currentIndex, priorIndex)
            {
                // Suppress (skip) "Warning" step if the user is old enough.
                if (currentIndex === 2 && Number($("#age").val()) >= 18)
                {
                    $(this).steps("next");
                }

                /*
                // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                if (currentIndex === 2 && priorIndex === 3)
                {
                    $(this).steps("previous");
                }
                */
            },
            onFinishing: function (event, currentIndex)
            {
                var form = $(this);

                var j = 0;

                for(i=1;i<10;i++) {
                    name = "input" + i;
                    hidden = $('[name=' + name + ']').val();
                    if (hidden) {
                        j = 1;
                        break;
                    }
                    console.log(name);
                    console.log(hidden);
                }

                // Disable validation on fields that are disabled.
                // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                form.validate().settings.ignore = ":disabled";

                // Start validation; Prevent form submission if false

                if (j == 1) {
                    return form.valid();
                } else {
                    swal({
                        title: "企画が選択されてません",
                        text: "検索するには、企画を１つ以上選択してください",
                        type: "warning",
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "OK",
                        closeOnConfirm: false
                    });

                }
            },
            onFinished: function (event, currentIndex)
            {
                var form = $(this);

                // Submit form input
                form.submit();
            }
        }).validate({
            errorPlacement: function (error, element)
            {
                element.before(error);
            },
            rules: {
                confirm: {
                    equalTo: "#password"
                }
            }
        });

        //iCheck
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
        $('input').on('ifChecked', function(event){
            $("#jQuery1").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQuery2").toggle();
        });

        //clockpicker
        var input = $('#clock1').clockpicker({
            placement: 'bottom',
            align: 'left',
            //autoclose: true,
            'default': 'now'
        });
        $('#clock2').clockpicker({
            placement: 'bottom',
            align: 'left',
            //autoclose: true,
        });

        $('#input-clock1').change(function() {
            if ($('#input-clock1').val) 
            $("#clockText1").text($('#input-clock1').val());
        });
        $('#input-clock2').change(function() {
            $("#clockText2").text($('#input-clock2').val());
        });

        //select2
        $(".select2_demo_1").select2();
        $(".select2_demo_2").select2();
        $(".select2_demo_3").select2({
            placeholder: "Select a state",
            allowClear: true
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox1").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush1").click(function(){
            $("#jQueryPush1").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox1").toggle();
        });

        $("#jQueryBox1").click(function(){
            $("#jQueryPush1").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox1").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox2").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush2").click(function(){
            $("#jQueryPush2").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox2").toggle();
        });

        $("#jQueryBox2").click(function(){
            $("#jQueryPush2").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox2").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox3").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush3").click(function(){
            $("#jQueryPush3").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox3").toggle();
        });

        $("#jQueryBox3").click(function(){
            $("#jQueryPush3").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox3").toggle();
        });
    });

    $(function(){
        // 「id="jQueryBox"」を非表示
        $("#jQueryBox4").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $("#jQueryPush4").click(function(){
            $("#jQueryPush4").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox4").toggle();
        });

        $("#jQueryBox4").click(function(){
            $("#jQueryPush4").toggle();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#jQueryBox4").toggle();
        });
    });

    //企画の項目を選んで表示
    $(function() {


        //キーワード検索
        $("#search_pid").on("select2:select", function () {
            pid = $(this).val();

            $.each(pid,
                function(index, elem) {
                    console.log(elem);

                    val = "#form_pid" + elem;

                    console.log(val);
                    $(val).show();

                    val1 = "input" + elem;
                    a = $('[name=' + val1 + ']').val(elem);
                    console.log(a);
                }
            );
        });

        //キーワード検索　消す
        $("#search_pid").on("select2:unselect", function (e) {
            val = "#form_pid" + e.params.data.id;
            //console.log(val);
            console.log(val);
            //console.log(e);


            $(val).hide();
            $('[name=val]').val();


        });



        $("#dropmenu").click(function (e) {
            e.stopPropagation(); // 追加
        });
        $("#dropmenu li").click(function (e) {
            e.stopPropagation(); // 追加
        });


    });

    $(function() {
        $("#pid1 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid1").toggle();
            $("#pid1 a").toggleClass("highlight");
            $("[name=input1]").val("1");
        });
        $("#pid2 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid2").toggle();
            $("#pid2 a").toggleClass("highlight");
            $("[name=input2]").val(2);
        });
        $("#pid3 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid3").toggle();
            $("#pid3 a").toggleClass("highlight");
            $("[name=input3]").val(3);
        });
        $("#pid4 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid4").toggle();
            $("#pid4 a").toggleClass("highlight");
            $("[name=input4]").val(4);
        });
        $("#pid5 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid5").toggle();
            $("#pid5 a").toggleClass("highlight");
            $("[name=input5]").val(5);
        });
        $("#pid6 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid6").toggle();
            $("#pid6 a").toggleClass("highlight");
            $("n[ame=input6]").val(6);
        });
        $("#pid7 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid7").toggle();
            $("#pid7 a").toggleClass("highlight");
            $("[name=input7]").val(7);
        });
        $("#pid8 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid8").toggle();
            $("#pid8 a").toggleClass("highlight");
            $("[name=input8]").val(8);
        });
        $("#pid9 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid9").toggle();
            $("#pid9 a").toggleClass("highlight");
            $("[name=input9]").val(9);
        });
        $("#pid10 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid10").toggle();
            $("#pid10 a").toggleClass("highlight");
            $("[name=input10]").val(10);
        });
        $("#pid11 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid11").toggle();
            $("#pid11 a").toggleClass("highlight");
            $("[name=input11]").val(11);
        });
        $("#pid12 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid12").toggle();
            $("#pid12 a").toggleClass("highlight");
            $("[name=input12]").val(12);
        });
        $("#pid13 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid13").toggle();
            $("#pid13 a").toggleClass("highlight");
            $("[name=input13]").val(13);
        });
        $("#pid14 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid14").toggle();
            $("#pid14 a").toggleClass("highlight");
            $("[name=input14]").val(14);
        });
        $("#pid15 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid15").toggle();
            $("#pid15 a").toggleClass("highlight");
            $("[name=input15]").val(15);
        });
        $("#pid16 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid16").toggle();
            $("#pid16 a").toggleClass("highlight");
            $("[name=input16]").val(16);
        });
        $("#pid1 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid17").toggle();
            $("#pid17 a").toggleClass("highlight");
            $("[name=input17]").val(17);
        });
        $("#pid18 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid18").toggle();
            $("#pid18 a").toggleClass("highlight");
            $("[name=input18]").val(18);
        });
        $("#pid19 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid19").toggle();
            $("#pid19 a").toggleClass("highlight");
            $("[name=input19]").val(19);
        });
        $("#pid20 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid20").toggle();
            $("#pid20 a").toggleClass("highlight");
            $("[name=input20]").val(20);
        });
        $("#pid21 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid21").toggle();
            $("#pid21 a").toggleClass("highlight");
            $("[name=input21]").val(21);
        });
        $("#pid22 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid22").toggle();
            $("#pid22 a").toggleClass("highlight");
            $("[name=input22]").val(22);
        });
        $("#pid23 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid23").toggle();
            $("#pid23 a").toggleClass("highlight");
            $("[name=input23]").val(23);
        });
        $("#pid24 a").click(function () {
            console.log(<?php echo $i; ?>);
            $("#form_pid24").toggle();
            $("#pid24 a").toggleClass("highlight");
            $("[name=input24]").val(24);
        });
    });

    $(document).ready(function () {

        $('#ap').click(function (e) {
            e.stopPropagation();
            swal({
                title: "工学部応用物理系ってなあに？",
                text: "You will not be able to recover this imaginary file!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "詳細が知りたい！",
                closeOnConfirm: false,
                allowOutsideClick: true,
            }, function () {
                window.location.href = "";
            });
        });
    });

    //ページ内ゆっくり遷移

    $(function(){
        $('a[href="#id"]').click(function(){
            var speed = 500;
            var href= $(this).attr("href");
            var target = $('#id');
            var position = target.offset().top;
            $("html, body").animate({scrollTop:position}, speed, "swing");
            return false;
        });
    });




    /*
     $("#pid<?php echo $i; ?> a").click(function () {
     $("#form_pid<?php echo $i; ?>").toggle(
     function () {
     $("#pid<?php echo $i; ?> a").css("background-color", "#ff1111");
     },
     function () {
     $("#pid<?php echo $i; ?> a").css("background-color","#ffe222");
     }
     );
     });
     */

    //var $eventSelect = $("#search_pid");

    //$eventSelect.on("change", function (e) { log("change"); });

    //キーワード検索用

    /*
     $('#search_pid').on('select2:select',function(e){
     val = ($(this).val());
     console.log(val);
     });
     */




    /*$("#form_pid".val).toggle();
     e.stopPropagation(); // 追加
     */
    //$("#pid".val." a").toggleClass("highlight");
    //$('[name="input".val]').val(<?php echo $i; ?>);



</script>

</body>

</html>

