<div id="tab-1" class="tab-pane active">
    <div class="panel-body">
        <div class="full-height-scroll">
            <input id="search1" type="text" class="form-control" value="" placeholder="企画名・建物名・団体名で検索できます。"/>

            <div style="overflow:scroll; height: 360px;">
                <ul id="search-all" class="list-group clear-list m-t">

                    <?php foreach ($this->data_all as $key => $item) : ?>
                        <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                            <span class="pull-right" style="width: 25%; text-align: right;">
                                <?php echo $item['pd_body']; ?>
                            </span>
                            <span class="pull-right m-r-lg" style="width:20%; text-align: right;">
                                <?php echo $item['pp_place']; ?>
                            </span>
                            <span class="pull-right m-r-lg" style="width:20%; text-align: right;">
                                <?php echo $item['pt_start']; ?>
                            </span>
                            <div class="i-checks">
                                <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p" name="select-p"> <i></i> <?php echo $item['pd_name']; ?> </label>
                            </div>
                        </li>
                    <?php endforeach; ?>

                </ul>
            </div>

            <!--<table class="table table-striped table-hover">
                <tbody>
                <tr>
                    <span class="help-block m-b-none">行きたい企画の名称,団体名,場所などの文字列を入力してください。</span><br>

                    <select class="select2_demo_1 form-control" id="search_pid" style="width:100%;" multiple="multiple">
                        <option value=""></option>
                        <?php foreach ($this->data as $item) : ?>
                            <option value="<?php echo $item['pd_pid']; ?>"><?php echo $item['pd_name']."　（".$item['pd_body']."　".$this->contents['list']['area'][$item['area']]."　".$this->contents['list'][$item['area']][$item['place_index']]; ?>）</option>
                        <?php endforeach; ?>
                    </select>
                </tr>
                </tbody>
            </table>-->
        </div>
    </div>
</div>
<div id="tab-2" class="tab-pane">
    <div class="panel-body" style="height:480px;overflow: scroll;">
        <div class="full-height-scroll">
            <div class="table-responsive">
                <div class="row">
                    <?php foreach ($this->data_genre as $key => $val) : ?>
                        <div class="col-sm-2">
                            <div id="PushGenre<?php echo $key; ?>" class="genre-push contact-box m-b-sm" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                <input type="hidden" name="name" value="<?php echo $key; ?>">
                                <h3><strong><?php echo $val['name']; ?></strong></h3>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <?php foreach ($this->data_genre as $key => $val) : ?>
                    <div class="row">
                        <div id="BoxGenre<?php echo $key; ?>" class="genre-box contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                            <?php foreach ($val['info'] as $i => $item) : ?>
                                <?php echo ($i%4 == 0) ? '<div class="row m-n">' : ''; ?>
                                <div class="col-sm-3">
                                    <button type="button" class="btn btn-open btn-<?php echo $this->color[$i%5]; ?> btn-lg btn-outline m-b-md btn-block">
                                        <?php echo $item['gd_detail_label']; ?>
                                        <input type="hidden" name="btn-val" value="genre<?php echo $item['gd_pid']; ?>">
                                    </button>
                                    <div class="select-box m-b-md" id="genre<?php echo $item['gd_pid']; ?>">
                                        <ul class="list-group clear-list m-t">
                                            <?php foreach ($item['data'] as $key2 => $item2) : ?>
                                                <li class="list-group-item <?php echo ($key2 == 0) ? 'fist-item' : ''; ?>">
                                                    <span class="pull-right">
                                                        <?php echo $item2['pt_start']; ?>
                                                    </span>
                                                    <div class="i-checks">
                                                        <label> <input type="checkbox" value="<?php echo $item2['ps_pid']; ?>" class="select-p"> <i></i> <?php echo $item2['pd_name']; ?> </label>
                                                    </div>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                                <?php echo ($i%4 == 3 || !$val['info'][$i+1]) ? '</div>' : ''; ?>
                            <?php endforeach; ?>
                            <?php foreach ($val['info'] as $i => $item) : ?>

                            <?php endforeach; ?>

                        </div>
                    </div>
                <?php endforeach; ?>

            </div>
        </div>
    </div>
</div>


<div id="tab-3" class="tab-pane">
    <div class="panel-body">
        <div class="full-height-scroll">
            <div class="table-responsive">
                <div class="row">
                    <?php foreach ($this->data_area as $key => $val) : ?>
                        <div class="col-sm-3">
                            <div id="PushArea<?php echo $key; ?>" class="area-push contact-box m-b-sm" style="background-image: url(/img/nougaku.jpg);background-size: cover; cursor: pointer;">
                                <input type="hidden" name="name" value="<?php echo $key; ?>">
                                <h3><strong><?php echo $val['name']; ?></strong></h3>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <?php foreach ($this->data_area as $key => $val) : ?>
                    <div class="row">
                        <div id="BoxArea<?php echo $key; ?>" class="area-box contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                            <?php foreach ($val['info'] as $i => $item) : ?>
                                <?php echo ($i%4 == 0) ? '<div class="row m-n">' : ''; ?>
                                <div class="col-sm-3">
                                    <button type="button" class="btn btn-open btn-<?php echo $this->color[$i%5]; ?> btn-lg btn-outline m-b-md btn-block">
                                        <?php echo $item['bd_label']; ?>
                                        <input type="hidden" name="btn-val" value="area<?php echo $item['bd_pid']; ?>">
                                    </button>
                                    <div class="select-box m-b-md" id="area<?php echo $item['bd_pid']; ?>">
                                        <ul class="list-group clear-list m-t">

                                            <?php foreach ($item['data'] as $key2 => $item2) : ?>
                                                <li class="list-group-item <?php echo ($key2 == 0) ? 'fist-item' : ''; ?>">
                                                    <span class="pull-right">
                                                        <?php echo $item2['pt_start']; ?>
                                                    </span>
                                                    <div class="i-checks">
                                                        <label> <input type="checkbox" value="<?php echo $item2['ps_pid']; ?>" class="select-p"> <i></i> <?php echo $item2['pd_name']; ?> </label>
                                                    </div>
                                                </li>
                                            <?php endforeach; ?>

                                        </ul>
                                    </div>
                                </div>
                                <?php echo ($i%4 == 3 || !$val['info'][$i+1]) ? '</div>' : ''; ?>
                            <?php endforeach; ?>
                            <?php foreach ($val['info'] as $i => $item) : ?>

                            <?php endforeach; ?>

                        </div>
                    </div>
                <?php endforeach; ?>


            </div>
        </div>
    </div>
</div>
<div id="tab-4" class="tab-pane">
    <div class="panel-body" style="height:540px;overflow: scroll;">
        <div class="full-height-scroll">
            <ul class="list-group clear-list m-t">

            <?php foreach ($this->data_rec as $key => $item) : ?>
                <li class="list-group-item <?php echo ($key == 0) ? 'fist-item' : ''; ?>">
                    <span class="pull-right">
                        <?php echo $item['pt_start']; ?>
                    </span>
                    <div class="i-checks">
                        <label> <input type="checkbox" value="<?php echo $item['ps_pid']; ?>" class="select-p"> <i></i> <?php echo $item['pd_name']; ?> </label>
                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){

        $('input#search1').on('keyup', function(){
            console.log($(this).val());
            Search($(this).val());
        });

    });

    function Search(keyword) {

        var regExp = new RegExp(keyword);

        $('#search-all').find('li').hide().each(function(){
            var li = $(this);
            $(this).find('label').each(function(){
                if ($(this).text().match(regExp)) {
                    li.show();
                }
            });
            $(this).find('span').each(function(){
                if ($(this).text().match(regExp)) {
                    li.show();
                }
            });
        });
    }

    $(function(){
    //iCheck
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });

    //genre
    $(function(){
        // 「id="jQueryBox"」を非表示
        $(".genre-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".genre-push").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $(".genre-push").hide();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#BoxGenre" + key).show();
        });
        $(".genre-box").click(function(e){
            e.stopPropagation();
            $(".genre-push").show();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $(".genre-box").hide();
        });
    });

    //area
    $(function(){
    // 「id="jQueryBox"」を非表示
        $(".area-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".area-push").click(function(){
            var key = $(this).find('input[name="name"]').val();
            $(".area-push").hide();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $("#BoxArea" + key).show();
        });

        $(".area-box").click(function(e){
            $(".area-push").show();
            // 「id="jQueryBox"」の表示、非表示を切り替える
            $(".area-box").hide();
        });
    });

    $(function(){
    // 「id="jQueryBox"」を非表示
        $(".select-box").css("display", "none");

        // 「id="jQueryPush"」がクリックされた場合
        $(".btn-open").click(function(e){
            e.stopPropagation();
            var key = $(this).find('input[name="btn-val"]').val();
            //$('.select-box').hide();
            $("div#" + key).toggle();
        });
    });

    $(function() {
        $('.last-conf').hide();

        $('input.select-p').on('ifChecked', function(event) {
            var val = $(this).val();
            console.log(val);
            $('input[value="' + val + '"]').iCheck('check');
            $('li#' + val).show();
        });

        $('input.select-p').on('ifUnchecked', function(event) {
            var val = $(this).val();
            console.log(val);
            $('input[value="' + val + '"]').iCheck('uncheck');
            $('li#' + val).hide();
        });
    });
</script>