<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>五月祭企画展示 経路探索</title>

    <link href="static_web/Static_Full_Version/css/bootstrap.min.css" rel="stylesheet">
    <link href="static_web/Static_Full_Version/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Toastr style -->
    <link href="static_web/Static_Full_Version/css/plugins/toastr/toastr.min.css" rel="stylesheet">

    <link href="static_web/Static_Full_Version/css/animate.css" rel="stylesheet">
    <link href="static_web/Static_Full_Version/css/style.css" rel="stylesheet">

</head>

<body>

<div id="wrapper">
    <div id="page-wrapper" class="gray-bg" style="margin-left: 0px;">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form role="search" class="navbar-form-custom" action="search_results.html">
                        <div class="form-group">
                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                        </a>
                        <ul class="dropdown-menu dropdown-messages">
                            <li>
                                <div class="dropdown-messages-box">
                                    <a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="img/a7.jpg">
                                    </a>
                                    <div class="media-body">
                                        <small class="pull-right">46h ago</small>
                                        <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                        <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="dropdown-messages-box">
                                    <a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="img/a4.jpg">
                                    </a>
                                    <div class="media-body ">
                                        <small class="pull-right text-navy">5h ago</small>
                                        <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                        <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="dropdown-messages-box">
                                    <a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="img/profile.jpg">
                                    </a>
                                    <div class="media-body ">
                                        <small class="pull-right">23h ago</small>
                                        <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                        <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="text-center link-block">
                                    <a href="mailbox.html">
                                        <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="mailbox.html">
                                    <div>
                                        <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="profile.html">
                                    <div>
                                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                        <span class="pull-right text-muted small">12 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="grid_options.html">
                                    <div>
                                        <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                        <span class="pull-right text-muted small">4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="text-center link-block">
                                    <a href="notifications.html">
                                        <strong>See All Alerts</strong>
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>


                    <li>
                        <a href="login.html">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>

            </nav>
        </div>
        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-10">
                <h2>五月祭企画展示 経路探索 by工學博覧会</h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a>App Views</a>
                    </li>
                    <li class="active">
                        <strong>Clients</strong>
                    </li>
                </ol>
            </div>
            <div class="col-lg-2">

            </div>
        </div>
        <div class="wrapper wrapper-content  animated fadeInRight">
            <div class="row">
                <div class="col-sm-12">
                    <div class="ibox">
                        <div class="ibox-content">
                            <span class="text-muted small pull-right">Last modification: <i class="fa fa-clock-o"></i> 2:10 pm - 12.06.2014</span>
                            <h2>Clients</h2>
                            <p>
                                All clients need to be verified before you can send email and set a project.
                            </p>
                            <div class="clients-list">

                                <div class="tabs-container">
                                    <div class="tabs-left">
                                        <ul class="nav nav-tabs">
                                            <!--<span class="pull-right small text-muted">1406 Elements</span>-->
                                            <li class="active"><a data-toggle="tab" href="#tab-1"><i class="fa fa-user"></i> キーワード検索</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-2"><i class="fa fa-briefcase"></i> ジャンル検索</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-3"><i class="fa fa-briefcase"></i> エリア検索</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-4"><i class="fa fa-briefcase"></i> おすすめ・ピックアップ企画</a></li>
                                        </ul>

                                        <div class="tab-content">
                                            <div id="tab-1" class="tab-pane active">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">
                                                            <table class="table table-striped table-hover">
                                                                <tbody>
                                                                <tr>
                                                                    <div class="input-group">
                                                                        <input type="text" class="input form-control" placeholder="ここに検索したい企画名,団体名,場所などの文字列を入力してください">
                                                                        <span class="input-group-btn">
                                                                            <button type="button" class="btn btn btn-primary"> <i class="fa fa-search"></i> Search</button>
                                                                        </span>
                                                                    </div>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                            <div id="tab-2" class="tab-pane">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">

                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>展示実演</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['exhibition'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'exhibition' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>参加型</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['join'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'join' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>

                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>講演会・評論会</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['lec_or_critic'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'lec_or_critic' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>パフォーマンス</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['performance'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'performance' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>

                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>音楽</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['music'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'music' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                            <div id="tab-3" class="tab-pane">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>農学部エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['no_dept'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'no_dept' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?><br>
                                                                                                                <div style="text-align: right;"><small class="media-body text-muted"><?php echo $item['body']; ?></small></div>
                                                                                                            </li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/kougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>工学部エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['ko_dept'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'ko_dept' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/yasuko.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>安田講堂エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['yasuko'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'yasuko' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/akamon.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>赤門エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['akamon'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'akamon' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="tab-4" class="tab-pane">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">
                                                            <table class="table table-striped table-hover">
                                                                <tbody>
                                                                <?php foreach ($this->data as $item) : ?>
                                                                    <?php if ($item['recommend_flg'] == 1) : ?>
                                                                        <tr>
                                                                            <td class="client-avatar"><img alt="image" src="img/a2.jpg"> </td>
                                                                            <td><a data-toggle="tab" href="#contact-1" class="client-link"><?php echo $item['name']; ?></a></td>
                                                                            <td><?php echo $item['body']; ?></td>
                                                                            <td class="contact-type"><i class="fa fa-envelope"> </i></td>
                                                                            <td><?php echo $this->contents['list']['place_index'][$item['place_index']]; ?></td>
                                                                            <td class="client-status"><span class="label label-primary"></span></td>
                                                                        </tr>
                                                                    <?php endif; ?>
                                                                <?php endforeach; ?>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>




        <!--しょーんくん-->



        <div class="footer">
            <div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2014-2017
            </div>
        </div>

    </div>
</div>



<!-- Mainly scripts -->
<script src="static_web/Static_Full_Version/js/jquery-3.1.1.min.js"></script>
<script src="static_web/Static_Full_Version/js/bootstrap.min.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="static_web/Static_Full_Version/js/inspinia.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/pace/pace.min.js"></script>

</body>
</html>
