<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>五月祭企画展示 経路探索</title>



    <link href="static_web/Static_Full_Version/css/bootstrap.min.css" rel="stylesheet">
    <link href="static_web/Static_Full_Version/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Toastr style -->
    <link href="static_web/Static_Full_Version/css/plugins/toastr/toastr.min.css" rel="stylesheet">

    <link href="static_web/Static_Full_Version/css/animate.css" rel="stylesheet">
    <link href="static_web/Static_Full_Version/css/style.css" rel="stylesheet">

    <!-- chosen -->
    <link href="static_web/Static_Full_Version/css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">

    <!-- checkbox -->
    <link href="static_web/Static_Full_Version/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">

    <!-- select2 -->
    <link href="static_web/Static_Full_Version/css/plugins/select2/select2.min.css" rel="stylesheet">

    <!-- switchery -->
    <!--<link href="static_web/Static_Full_Version/css/plugins/switchery/switchery.css" rel="stylesheet">-->

    <!-- checkboxその２-->
    <link href="static_web/Static_Full_Version/css/plugins/iCheck/custom.css" rel="stylesheet">

    <!-- multi-select-->
    <link href="css/multi-select.css" type="text/css" rel="stylesheet">


</head>

<body>

<div id="wrapper">
    <div id="page-wrapper" class="gray-bg" style="margin-left: 0px;">
        <div class="row wrapper border-bottom white-bg page-heading" style="min-height: 720px; background-image: url(/img/FotorCreated.jpg);background-size: cover;">
            <div class="col-lg-10">
                <p style="text-align:center; color: #fffff0; font-size:10em;">MAY FESTIVAL<br>2017 SEARCH</p>
                <!--
                <div style="text-align: center;">
                    <div class="radio radio-info radio-inline">
                        <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                        <label for="inlineRadio1"> １日目 </label>
                    </div>
                    <div class="radio radio-danger radio-inline">
                        <input type="radio" id="inlineRadio2" value="option2" name="radioInline">
                        <label for="inlineRadio2"> ２日目 </label>
                    </div>
                    <div class="radio radio-inline">
                        <input type="radio" id="inlineRadio3" value="option3" name="radioInline">
                        <label for="inlineRadio3"> 両日 </label>
                    </div>
                </div>
                -->
                <div class="row">

                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="ibox ibox-content" style="background-color: rgba(255, 255,255, 0.5);">

                            <div style="text-align: center;">
                                <div class="checkbox-inline i-checks"><input id="day0" type="radio" name="radio-kun" id="radio0" value="0" checked="checked"  /> <label> <i></i> １日目 </label></div>
                                <div class="checkbox-inline i-checks"><input id="day1" type="radio" name="radio-kun" id="radio1" value="1"  /> <label> <i></i> ２日目 </label></div>
                                <!--<div class="checkbox-inline i-checks"><label> <input type="radio" value="option1" name="a"> <i></i> 両日 </label></div>-->
                            </div>

                            <div class="form-group" style="text-align:center;">
                                <label class="font-normal">滞在時間  </label>
                                <div style="display:inline">
                                    <div style="display:inline">
                                        <select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                            <?php for ($i=9;$i<16;$i++): ?>
                                        <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>:
                                    <div style="display:inline">
                                        <select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                            <?php for ($i=0;$i<6;$i++): ?>
                                                <option value="United States"><?php echo $i; ?>0</option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                                <label class="font-normal">〜</label>
                                <div style="display:inline;">
                                    <div style="display:inline">
                                        <select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                            <?php for ($i=10;$i<17;$i++): ?>
                                                <option value="United States"><?php echo $i; ?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>:
                                    <div style="display:inline">
                                        <select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                            <?php for ($i=0;$i<6;$i++): ?>
                                                <option value="United States"><?php echo $i; ?>0</option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>
                                <br><br>
                                <div style="text-align:center;"><a href="#step2" data-scroll type="button" class="btn btn-outline btn-primary btn-lg">GO</a></div>
                            </div>
                        </div>
                        <div class="col-md-3"></div>

                    </div>
                </div>
            </div>
            <div class="col-lg-2">

            </div>
        </div>


        <div class="row wrapper border-bottom white-bg page-heading" style="min-height: 700px; background-image: url(/img/library.jpg);background-size: cover; margin-top:50px;">
            <div class="wrapper wrapper-content animated fadeInRight">
                <div class="row">
                    <div class="col-sm-12">
                        <div id="step2" class="ibox">
                            <div class="ibox-content" style="height:720px">
                                <h2>Where will you start? -- あなたの現在地を教えてください！</h2>
                                <p>
                                    近くに何が見えますか？<br>
                                    今見てきた企画は何ですか？<br>
                                    ーーー地図上でおおよその現在地を特定できます！
                                </p>

                                <!--<select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                    <option value="">Select</option>
                                    <?php foreach ($this->result as $item): ?>
                                        <option value=""><?php echo $item['fw_name']; ?></option>
                                    <?php endforeach; ?>
                                </select>-->


                                <div class="form-group">
                                    <div class="row">

                                        <div class="col-md-5">
                                            <select class="select2_demo_1 form-control">
                                                    <option value="">近くに見える建物の名称,たった今見てきた企画名を記入</option>
                                                <?php foreach ($this->result as $item): ?>
                                                    <option value=""><?php echo $item['fw_name']; ?>　（<small style="text-align:right;"><?php echo $item['fw_area']; ?>　<?php echo $item['fw_place_index']; ?></small>）</option>
                                                <?php endforeach; ?>
                                                <?php foreach ($this->data as $item) : ?>
                                                    <option value=""><?php echo $item['name']."　（".$item['body']."　".$this->contents['list']['area'][$item['area']]."　".$this->contents['list'][$item['area']][$item['place_index']]; ?>）</option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>

                                        <div class="col-md-7">

                                            <div id="usa_map"></div>

                                            <!--<object data="/pdf/map.pdf" type="application/pdf" width="700px" height="500px"></object>-->
                                        </div>
                                    </div>
                                    <div style="text-align:right;"><a href="#step3" data-scroll type="button" class="btn btn-outline btn-primary btn-lg">GO</a></div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        </div>

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-sm-8">
                    <div id="step3" class="ibox">
                        <div class="ibox-content" style="height:720px">
                            <span class="text-muted small pull-right">Last modification: <i class="fa fa-clock-o"></i> 2:10 pm - 12.06.2014</span>
                            <h2>Please select projects you want to watch!</h2>
                            <p>
                                行きたい企画を選んでください！ 色んな方法で調べることができるので、あなたに合った企画がきっと見つかるでしょう。
                            </p>

                            <div class="tabs-container">
                                <div class="">
                                    <ul class="nav nav-tabs">
                                        <!--<span class="pull-right small text-muted">1406 Elements</span>-->
                                        <li class="active"><a data-toggle="tab" href="#tab-1"><i class="fa fa-user"></i> キーワード検索</a></li>
                                        <li class=""><a data-toggle="tab" href="#tab-2"><i class="fa fa-briefcase"></i> ジャンル検索</a></li>
                                        <li class=""><a data-toggle="tab" href="#tab-3"><i class="fa fa-briefcase"></i> エリア検索</a></li>
                                        <li class=""><a data-toggle="tab" href="#tab-4"><i class="fa fa-briefcase"></i> おすすめ・ピックアップ企画</a></li>
                                        <li class=""><a data-toggle="tab" href="#tab-5"><i class="fa fa-briefcase"></i> これから開演予定の企画検索</a></li>
                                    </ul>

                                    <div class="tab-content">
                                        <div id="tab-1" class="tab-pane active">
                                            <div class="panel-body">
                                                <div class="full-height-scroll">
                                                    <div class="table-responsive">
                                                        <table class="table table-striped table-hover">
                                                            <tbody>
                                                            <tr>
                                                                <select class="select2_demo_1 form-control">
                                                                    <option value="">行きたい企画の名称,団体名,場所などの文字列を入力してください</option>
                                                                    <?php foreach ($this->data as $item) : ?>
                                                                        <option value=""><?php echo $item['name']."　（".$item['body']."　".$this->contents['list']['area'][$item['area']]."　".$this->contents['list'][$item['area']][$item['place_index']]; ?>）</option>
                                                                    <?php endforeach; ?>
                                                                </select>
                                                            </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div id="tab-2" class="tab-pane">
                                            <div class="panel-body" style="height:540px;overflow: scroll;">
                                                <div class="full-height-scroll">
                                                    <div class="table-responsive">

                                                        <div class="row">
                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                    <h3><strong>展示実演</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['exhibition'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'exhibition' && $item['place_index'] == $key) : ?>
                                                                                                        <li class="list-group-item">
                                                                                                            <?php echo $item['name']; ?></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                    <h3><strong>参加型</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['join'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'join' && $item['genre_detail'] == $key) : ?>
                                                                                                        <li class="list-group-item">
                                                                                                            <?php echo $item['name']; ?></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                        </div>

                                                        <div class="row">
                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                    <h3><strong>講演会・評論会</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['lec_or_critic'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'lec_or_critic' && $item['genre_detail'] == $key) : ?>
                                                                                                        <li class="list-group-item">
                                                                                                            <?php echo $item['name']; ?></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                    <h3><strong>パフォーマンス</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['performance'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'performance' && $item['genre_detail'] == $key) : ?>
                                                                                                        <li class="list-group-item">
                                                                                                            <?php echo $item['name']; ?></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                        </div>

                                                        <div class="row">
                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                    <h3><strong>音楽</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['music'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['genre'] == 'music' && $item['genre_detail'] == $key) : ?>
                                                                                                        <li class="list-group-item">
                                                                                                            <?php echo $item['name']; ?></li>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                        </div>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div id="tab-3" class="tab-pane">
                                            <div class="panel-body" style="height:540px;overflow: scroll;">
                                                <div class="full-height-scroll">
                                                    <div class="table-responsive">
                                                        <div class="row">
                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                    <h3><strong>農学部エリア</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['no_dept'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'no_dept' && $item['place_index'] == $key) : ?>
                                                                                                        <a id=<?php echo $item['pid']; ?>>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?><br>
                                                                                                                <div style="text-align: right;"><small class="media-body text-muted"><?php echo $item['body']; ?></small></div>
                                                                                                            </li></a>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/kougaku.jpg);background-size: cover;">
                                                                    <h3><strong>工学部エリア</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['ko_dept'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'ko_dept' && $item['place_index'] == $key) : ?>
                                                                                                        <a id=<?php echo $item['pid']; ?>>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?>
                                                                                                                <div style="text-align: right;"><small class="media-body text-muted"><?php echo $item['body']; ?></small></div>
                                                                                                            </li></a>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/yasuko.jpg);background-size: cover;">
                                                                    <h3><strong>安田講堂エリア</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['yasuko'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'yasuko' && $item['place_index'] == $key) : ?>
                                                                                                        <a id=<?php echo $item['pid']; ?>>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?>
                                                                                                                <div style="text-align: right;"><small class="media-body text-muted"><?php echo $item['body']; ?></small></div>
                                                                                                            </li></a>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="col-sm-6">
                                                                <div class="contact-box" style="background-image: url(/img/akamon.jpg);background-size: cover;">
                                                                    <h3><strong>赤門エリア</strong></h3>
                                                                    <br><br><br><br><br>
                                                                    <div class="clearfix"></div>
                                                                    <div class="ibox float-e-margins border-bottom">
                                                                        <div class="ibox-title">
                                                                            <h5>Select</h5>
                                                                            <div class="ibox-tools">
                                                                                <a class="collapse-link">
                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <div class="ibox-content" style="display: none;">
                                                                            <ul class="list-group">
                                                                                <div class="ibox float-e-margins border-bottom">
                                                                                    <?php foreach ($this->contents['list']['akamon'] as $key => $place) : ?>
                                                                                        <div class="ibox-title">
                                                                                            <h5><?php echo $place; ?></h5>
                                                                                            <div class="ibox-tools">
                                                                                                <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                    <i class="fa fa-chevron-up"></i>
                                                                                                </a>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                            <ul class="list-group">
                                                                                                <?php foreach($this->data as $item) : ?>
                                                                                                    <?php if ($item['area'] == 'akamon' && $item['place_index'] == $key) : ?>
                                                                                                        <a id=<?php echo $item['pid']; ?>>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?>
                                                                                                                <div style="text-align: right;"><small class="media-body text-muted"><?php echo $item['body']; ?></small></div>
                                                                                                            </li>
                                                                                                        </a>
                                                                                                    <?php endif; ?>
                                                                                                <?php endforeach; ?>
                                                                                            </ul>
                                                                                        </div>
                                                                                    <?php endforeach; ?>
                                                                                </div>
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="tab-4" class="tab-pane">
                                            <div class="panel-body" style="height:540px;overflow: scroll;">
                                                <div class="full-height-scroll">
                                                    <div class="table-responsive">
                                                        <table class="table table-striped table-hover">
                                                            <tbody>
                                                            <?php foreach ($this->data as $item) : ?>
                                                                <?php if ($item['recommend_flg'] == 1) : ?>
                                                                    <tr>
                                                                        <td class="client-avatar"><img alt="image" src="img/a2.jpg"> </td>
                                                                        <td><a id=<?php echo $item['pid']; ?> class="client-link"><?php echo $item['name']; ?></a></td>
                                                                        <td><?php echo $item['body']; ?></td>
                                                                        <!--<td><small class="text-muted"><?php echo $this->contents['list']['area'][$item['area']]; ?></small></td>-->
                                                                        <td><small class="text-muted"><?php echo $this->contents['list'][$item['area']][$item['place_index']]; ?></small></td>
                                                                        <!--<td class="contact-type"><i class="fa fa-envelope"> </i></td>
                                                                        <td class="client-status"><span class="label label-primary"></span></td>-->
                                                                        <td><button data-toggle="" href="" class="btn btn-outline btn-xs btn-warning">detail</button></td>
                                                                    </tr>
                                                                <?php endif; ?>
                                                            <?php endforeach; ?>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">

                    <div class="ibox">
                        <div class="ibox-content" style="height: 720px;position: fixed;z-index: 999;">
                            <!--<span class="text-muted small pull-right">Last modification: <i class="fa fa-clock-o"></i> 2:10 pm - 12.06.2014</span>-->
                            <h2>Check your search terms!</h2>
                            <p>
                                All clients need to be verified before you can send email and set a project.
                            </p>



                            <form action="search">
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <div style="text-align: center;">
                                            <div class="checkbox-inline i-checks"><label> <input type="radio" name="password" value="0" id="password0" checked="checked" /> <label> <i></i> １日目 </label></div>
                                            <div class="checkbox-inline i-checks"><label> <input type="radio" name="password" value="1" id="password1" /> <label> <i></i> ２日目 </label></div>
                                            <!--<div class="checkbox-inline i-checks"><label> <input type="radio" value="option1" name="a"> <i></i> 両日 </label></div>-->
                                        </div>
                                        <div class="form-group" style="text-align:center;">
                                            <!--<label class="font-normal">滞在時間  </label>-->
                                            <div style="display:inline">
                                                <div style="display:inline">
                                                    <select data-placeholder="Choose a Country..." class="chosen-select" style="width:20%"  tabindex="2">
                                                        <?php for ($i=9;$i<16;$i++): ?>
                                                            <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                                        <?php endfor; ?>
                                                    </select>
                                                </div>:
                                                <div style="display:inline">
                                                    <select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                                        <?php for ($i=0;$i<6;$i++): ?>
                                                            <option value="United States"><?php echo $i; ?>0</option>
                                                        <?php endfor; ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <label class="font-normal">〜</label>
                                            <div style="display:inline;">
                                                <div style="display:inline">
                                                    <select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                                        <?php for ($i=10;$i<17;$i++): ?>
                                                            <option value="United States"><?php echo $i; ?></option>
                                                        <?php endfor; ?>
                                                    </select>
                                                </div>:
                                                <div style="display:inline">
                                                    <select data-placeholder="Choose a Country..." class="chosen-select"  tabindex="2">
                                                        <?php for ($i=0;$i<6;$i++): ?>
                                                            <option value="United States"><?php echo $i; ?>0</option>
                                                        <?php endfor; ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>

                                <div style="text-align:center;"><small class="text-muted">ここに選択した企画が表示されます</small></div>

                                        <ul class="list-group">
                                    <?php foreach ($this->data as $item) : ?>
                                        <li class="list-group-item" style="display:none;" id=<?php echo $item['pid']; ?>><?php echo $item['name']; ?>
                                            <a id="close-link" style="float:right; color:#c4c4c4;">
                                                <i class="fa fa-times"></i></a>
                                            <small class="text-muted text-xs" style="float:right;margin-top:2px;"><?php echo $item['body']." ".$this->contents['list']['xs_area'][$item['area']]."　"; ?></small>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>

                                <div style="text-align:center;"><button type="submit" class="btn btn-outline btn-primary btn-lg">LET'S SEARCH</button></div>

                            </form>

                        </div>
                    </div>
                </div>

            </div>
            <body>

        </div>






        <!--しょーんくん-->


        <div class="footer">
            <div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>
            <div>
                <strong>Copyright</strong> 東京大学工学部応用物理系 &copy; 2017
            </div>
        </div>

    </div>
</div>



<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<script src="jquery.min.js" type="text/javascript"></script>
<script src="js/jquery.multi-select.js" type="text/javascript"></script>

<!-- Mainly scripts -->
<script src="static_web/Static_Full_Version/js/jquery-3.1.1.min.js"></script>
<script src="static_web/Static_Full_Version/js/bootstrap.min.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<!--<script src="static_web/Static_Full_Version/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>-->

<!-- Custom and plugin javascript -->
<script src="static_web/Static_Full_Version/js/inspinia.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/pace/pace.min.js"></script>

<!-- Chosen -->
<script src="static_web/Static_Full_Version/js/plugins/chosen/chosen.jquery.js"></script>


<!-- Select2 -->
<script src="static_web/Static_Full_Version/js/plugins/select2/select2.full.min.js"></script>

<!-- iCheck -->
<script src="static_web/Static_Full_Version/js/plugins/iCheck/icheck.min.js"></script>


<!-- DataMaps -->
<script src="static_web/Static_Full_Version/js/plugins/typehead/bootstrap3-typeahead.min.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/d3/d3.min.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/topojson/topojson.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/datamaps/datamaps.all.min.js"></script>

<!-- 検索項目の表示非表示-->
<script type="text/javascript">
    $(function() {
        <?php foreach($this->data as $item): ?>
            $('a[id=<?php echo $item['pid']; ?>]').click(function(){
                $('li[id=<?php echo $item['pid']; ?>]').show();
            });
        <?php endforeach; ?>
        $('li a[id="close-link"]').click(function(){
            $(this).parent().hide();
        });
    });
</script>

<!-- -->
<script>

    $(function() {
        $("[name='radio-kun']").click(function(){
            var num = $(":checked").val();
            if ( num == 1 ){
                $("#password1").prop("checked", true);
                $("#password0").prop("checked", false);
            } else {
                $("#password1").prop("checked", false);
                $("#password0").prop("checked", true);
            }
        });


    });



    /*$(function() {
        $("input[name='radio1']").click(function(){
            var num = $("[name='radio1']").index(this);
            if(num == 1){
                $('input[id="rd1"]').attr("checked", true);
                $('input[id="rd2"]').attr("checked", true);
            } else {
                $('input[id="rd1"]').attr("checked", true);
                $('input[id="rd2"]').attr("checked", true);
            }
        });

        /*$("[name='test']").click(function(){
            var num = $("[name='test']").index(this);
            if(num == 1){
                $("select").attr("disabled", false);
            } else {
                $("select").attr("disabled", true);
            }
        });*/
   /* });*/

</script>


<!--スムーススクロース-->
<script src="/js/smooth-scroll.js"></script>
<script>
    // スムーススクロールを起動する
    smoothScroll.init() ;
</script>

<!-- jQuery.jsの読み込み -->

<script type="text/javascript">
    $(function () {
        $('a[href^=#]').click(function() {
            var speed = 400;
            var href= $(this).attr("href");
            var target = $(href == "#" || href == "" ? 'html' : href);
            var position = target.offset().top;
            $('body,html').animate({scrollTop:position}, speed, 'swing');
            return false;
        });
    });
</script>


<script>

    $('.chosen-select').chosen({width: "15%"});

    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });


        $(".select2_demo_1").select2();
        $(".select2_demo_2").select2();
        $(".select2_demo_3").select2({
            placeholder: "Select a state",
            allowClear: true
        });

        var usa_map = new Datamap({
            element: document.getElementById("usa_map"),
            responsive: true,
            scope: 'usa',
            fills: {
                defaultFill: "#DBDAD6",
                active: "#2BA587"
            },
            geographyConfig: {
                highlightFillColor: '#1C977A',
                highlightBorderWidth: 0
            },
            data: {
                NE: { fillKey: "active" },
                CA: { fillKey: "active" },
                NY: { fillKey: "active" },
            }
        });

        orthographic_map.graticule();

        // Resize map on window resize
        $(window).on('resize', function() {
            setTimeout(function(){
                basic.resize();
                selected_map.resize();
            },100)
        });


        $('input[name=right]').on('click', function() {
            move('s1', 's2');
        });

        $('input[name=left]').on('click', function() {
            move('s2', 's1');
        });

        var move = function(_this, target) {
            $('select[name=' + _this + '] option:selected').each(function() {
                $('select[name=' + target + ']').append($(this).clone());
                $(this).remove();
            });
        };
    });

</script>



</body>
</html>
