<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>五月祭企画展示 経路探索</title>

    <link href="static_web/Static_Full_Version/css/bootstrap.min.css" rel="stylesheet">
    <link href="static_web/Static_Full_Version/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Toastr style -->
    <link href="static_web/Static_Full_Version/css/plugins/toastr/toastr.min.css" rel="stylesheet">

    <link href="static_web/Static_Full_Version/css/animate.css" rel="stylesheet">
    <link href="static_web/Static_Full_Version/css/style.css" rel="stylesheet">

</head>

<body>

<div id="wrapper">
    <div id="page-wrapper" class="gray-bg" style="margin-left: 0px;">
        <div class="row wrapper border-bottom white-bg page-heading" style="height: 721px;">
            <div class="col-lg-10">
                <h2 style="text-align:center;">五月祭企画展示 経路探索 by工學博覧会</h2>
                <div style="text-align:center;"><a href="" type="button" class="btn btn-outline btn-default btn-lg">GO</a></div>
            </div>
            <div class="col-lg-2">

            </div>
        </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-sm-12">
                    <div class="ibox">
                        <div class="ibox-content">
                            <span class="text-muted small pull-right">Last modification: <i class="fa fa-clock-o"></i> 2:10 pm - 12.06.2014</span>
                            <h2>Clients</h2>
                            <p>
                                All clients need to be verified before you can send email and set a project.
                            </p>

                                <div class="tabs-container">
                                    <div class="tabs-left">
                                        <ul class="nav nav-tabs">
                                            <!--<span class="pull-right small text-muted">1406 Elements</span>-->
                                            <li class="active"><a data-toggle="tab" href="#tab-1"><i class="fa fa-user"></i> キーワード検索</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-2"><i class="fa fa-briefcase"></i> ジャンル検索</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-3"><i class="fa fa-briefcase"></i> エリア検索</a></li>
                                            <li class=""><a data-toggle="tab" href="#tab-4"><i class="fa fa-briefcase"></i> おすすめ・ピックアップ企画</a></li>
                                        </ul>

                                        <div class="tab-content">
                                            <div id="tab-1" class="tab-pane active">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">
                                                            <table class="table table-striped table-hover">
                                                                <tbody>
                                                                <tr>
                                                                    <div class="input-group">
                                                                        <input type="text" class="input form-control" placeholder="ここに検索したい企画名,団体名,場所などの文字列を入力してください">
                                                                        <span class="input-group-btn">
                                                                            <button type="button" class="btn btn btn-primary"> <i class="fa fa-search"></i> Search</button>
                                                                        </span>
                                                                    </div>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                            <div id="tab-2" class="tab-pane">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">

                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>展示実演</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['exhibition'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'exhibition' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>参加型</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['join'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'join' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>

                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>講演会・評論会</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['lec_or_critic'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'lec_or_critic' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>パフォーマンス</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['performance'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'performance' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>

                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>音楽</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['music'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['genre'] == 'music' && $item['genre_detail'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                            <div id="tab-3" class="tab-pane">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/nougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>農学部エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['no_dept'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'no_dept' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?><br>
                                                                                                                <div style="text-align: right;"><small class="media-body text-muted"><?php echo $item['body']; ?></small></div>
                                                                                                            </li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/kougaku.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>工学部エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['ko_dept'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'ko_dept' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/yasuko.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>安田講堂エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['yasuko'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'yasuko' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="contact-box" style="background-image: url(/img/akamon.jpg);background-size: cover;">
                                                                        <a href="profile.html">
                                                                            <h3><strong>赤門エリア</strong></h3>
                                                                            <br><br><br><br><br>
                                                                            <div class="clearfix"></div>
                                                                        </a>
                                                                        <div class="ibox float-e-margins border-bottom">
                                                                            <div class="ibox-title">
                                                                                <h5>Select</h5>
                                                                                <div class="ibox-tools">
                                                                                    <a class="collapse-link">
                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="ibox-content" style="display: none;">
                                                                                <ul class="list-group">
                                                                                    <div class="ibox float-e-margins border-bottom">
                                                                                        <?php foreach ($this->contents['list']['akamon'] as $key => $place) : ?>
                                                                                            <div class="ibox-title">
                                                                                                <h5><?php echo $place; ?></h5>
                                                                                                <div class="ibox-tools">
                                                                                                    <a data-toggle="collapse" href="#<?php echo $key; ?>">
                                                                                                        <i class="fa fa-chevron-up"></i>
                                                                                                    </a>
                                                                                                </div>
                                                                                            </div>
                                                                                            <div class="ibox-content collapse" id="<?php echo $key; ?>">
                                                                                                <ul class="list-group">
                                                                                                    <?php foreach($this->data as $item) : ?>
                                                                                                        <?php if ($item['area'] == 'akamon' && $item['place_index'] == $key) : ?>
                                                                                                            <li class="list-group-item">
                                                                                                                <?php echo $item['name']; ?></li>
                                                                                                        <?php endif; ?>
                                                                                                    <?php endforeach; ?>
                                                                                                </ul>
                                                                                            </div>
                                                                                        <?php endforeach; ?>
                                                                                    </div>
                                                                                </ul>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="tab-4" class="tab-pane">
                                                <div class="panel-body">
                                                    <div class="full-height-scroll">
                                                        <div class="table-responsive">
                                                            <table class="table table-striped table-hover">
                                                                <tbody>
                                                                <?php foreach ($this->data as $item) : ?>
                                                                    <?php if ($item['recommend_flg'] == 1) : ?>
                                                                        <tr>
                                                                            <td class="client-avatar"><img alt="image" src="img/a2.jpg"> </td>
                                                                            <td><a data-toggle="tab" href="#contact-1" class="client-link"><?php echo $item['name']; ?></a></td>
                                                                            <td><?php echo $item['body']; ?></td>
                                                                            <td class="contact-type"><i class="fa fa-envelope"> </i></td>
                                                                            <td><?php echo $this->contents['list']['place_index'][$item['place_index']]; ?></td>
                                                                            <td class="client-status"><span class="label label-primary"></span></td>
                                                                        </tr>
                                                                    <?php endif; ?>
                                                                <?php endforeach; ?>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>




        <!--しょーんくん-->


<!--
        <div class="footer">
            <div class="pull-right">
                10GB of <strong>250GB</strong> Free.
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2014-2017
            </div>
        </div>-->

    </div>
</div>



<!-- Mainly scripts -->
<script src="static_web/Static_Full_Version/js/jquery-3.1.1.min.js"></script>
<script src="static_web/Static_Full_Version/js/bootstrap.min.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="static_web/Static_Full_Version/js/inspinia.js"></script>
<script src="static_web/Static_Full_Version/js/plugins/pace/pace.min.js"></script>

</body>
</html>
